//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Style.rc
//
#define IDS_SPOTNONE                    2
#define IDS_SPOTFONT                    3
#define IDS_SPOTSYMBOL                  4
#define IDS_SPOTPATTERN                 5
#define IDS_SPOTFLASH                   6
#define IDS_LINEINHERIT                 7
#define IDS_LINEEMPTY                   8
#define IDS_LINEALONE                   9
#define IDS_LINENORMAL                  10
#define IDS_LINESYMBOL                  11
#define IDS_LINERIVER                   12
#define IDS_FILLINHERIT                 13
#define IDS_FILLEMPTY                   14
#define IDS_FILLALONE                   15
#define IDS_FILLNORMAL                  16
#define IDS_FILLSYMBOL                  17
#define IDS_FILLLINEARGRADIENT          18
#define IDS_FILLRADIAL                  19
#define IDS_FILLPATTERN                 20
#define IDS_COLORGRAY                   21
#define IDS_COLORSPOT                   22
#define IDS_COLORPROCESS                23
#define IDS_SPOTSYMBOLFILTER            24
#define IDS_LINESYMBOLFILTER            25
#define IDS_FILLSYMBOLFILTER            26
#define IDS_PANE_LAYER                  27
#define IDS_NAME                        28
#define IDS_SYMBOL                      29
#define IDS_LAYERLOCKEDNOGEOM           30
#define IDS_LAYERNEEDSPOT               31
#define IDS_LAYERLOCKEDNOMOVEON         32
#define IDS_LAYERLOCKEDNOMOVEOFF        33
#define IDS_LAYERLOCKEDNOCOPY           34
#define IDS_LAYERLOCKEDNOCLONE          35
#define IDS_LAYERLOCKEDNODELETE         36
#define IDS_LAYERLOCKEDNOGROUP          37
#define IDS_LAYERLOCKEDNOUNGROUP        38
#define IDS_LAYERLOCKEDNOJOIN           39
#define IDS_LAYERLOCKEDNOMOVE           40
#define IDS_LAYERLOCKEDNOCLIP           41
#define IDS_LAYERLOCKEDNOINFO           42
#define IDS_LOCKEDNOLAYERDELETE         43
#define IDS_LAYER_NAME                  44
#define IDD_STYLE                       45
#define IDS_NONE                        46
#define IDD_SPOTPATTERN                 52
#define IDD_FILLALONE                   56
#define IDD_LINEALONE                   57
#define IDR_POPUP_EXPLORER              58
#define IDB_ICONIMAGE                   59
#define IDD_COLOR                       60
#define IDD_DASH                        61
#define IDB_CAPSSQUARE                  62
#define IDB_CAPSROUND                   63
#define IDB_CAPSFLAT                    64
#define IDB_JOINBEVEL                   65
#define IDB_JOINROUND                   66
#define IDB_JOINMITER                   67
#define IDD_SPOTSYMBOL                  68
#define IDD_LINESYMBOL                  69
#define IDD_FILLSYMBOL                  70
#define IDD_HINT                        71
#define IDD_FILLLINEARGRADIENT          73
#define IDD_FILLLINEAR                  73
#define IDD_FILLRADIAL                  74
#define IDD_COLORPROCESS                75
#define IDD_COLORSPOT                   76
#define IDD_COLORGRAY                   77
#define IDD_LINECTRL                    78
#define IDD_FILLCTRL                    79
#define IDD_LINERIVER                   80
#define IDD_FILLPATTERN                 81
#define IDD_SPOTCTRL                    82
#define IDD_SPOTFONT                    83
#define IDD_SPOTFLASH                   84
#define IDD_TEXTSTYLE0                  86
#define IDD_TEXTSTYLE2                  87
#define IDD_TEXTSTYLE1                  88
#define IDB_BACKGROUND                  100
#define IDB_BITMAP1                     101
#define IDB_FILLTYPES                   101
#define IDB_STROKETYPES                 102
#define IDD_GRADIENT                    102
#define IDB_ANNOTYPES                   103
#define IDD_TEXTSTYLE3                  103
#define IDB_SPOTTYPES                   104
#define IDB_RULER                       129
#define IDB_PENCIL                      130
#define IDC_TYPECOMBO                   133
#define IDC_EDITC                       134
#define IDC_EDITM                       135
#define IDC_EDITY                       136
#define IDC_EDITK                       137
#define IDC_SCROLLR                     138
#define IDC_SCROLLG                     139
#define IDC_SCROLLB                     140
#define IDC_SCROLLM                     141
#define IDC_SCROLLY                     142
#define IDC_EDITT                       143
#define IDC_FWIDTH                      144
#define IDC_EDITA                       144
#define IDC_SCROLLBAR                   149
#define IDC_LOAD                        150
#define IDC_RESOLUTION                  151
#define IDC_HEIGHT                      152
#define IDC_COLORS                      153
#define IDC_CHARLIST                    161
#define IDC_CHARSIZE                    163
#define IDC_SCROLLA                     166
#define IDC_GROUND                      169
#define IDC_ROUNDRECT                   170
#define IDC_BORDWIDTH                   171
#define IDC_GROUNDCOLOR                 172
#define IDC_BORDCOLOR                   173
#define IDC_PATTERNICON                 174
#define IDC_COUNT                       175
#define IDC_COLOR                       178
#define IDC_COLOR1                      179
#define IDC_COLOR2                      180
#define IDC_DASH                        182
#define IDC_SAMPLE                      185
#define IDC_SWF                         192
#define IDC_COMBOFILE                   193
#define IDC_IMAGELIST                   194
#define IDC_LIST1                       195
#define IDC_GROUPBOX                    198
#define IDC_HOLDER                      199
#define IDC_FONTSTYLES                  200
#define IDC_FILTERS                     201
#define IDC_HANGLE                      202
#define IDC_VANGLE                      203
#define IDC_FONTCOMBO                   204
#define IDC_HORZSCALE                   205
#define IDC_HORZSCALE2                  206
#define IDC_HORZSCALE3                  207
#define IDC_SYMBOLLIST                  208
#define IDC_PREVIEW                     209
#define IDC_SCALE                       210
#define IDC_FONTSIZE                    211
#define IDC_ANGLE                       212
#define IDC_WIDTH                       213
#define IDC_TWIDTH                      214
#define IDC_SCROLLT                     215
#define IDC_SCROLLK                     216
#define IDC_UNITSHOW                    217
#define IDC_SCROLLC                     218
#define IDC_EDITB                       219
#define IDC_EDITR                       220
#define IDC_EDITG                       221
#define IDC_NEWCOLOR                    222
#define IDC_OLDCOLOR                    223
#define IDC_CAPSQUARE                   224
#define IDC_CAPROUND                    225
#define IDC_JOINBEVEL                   226
#define IDC_JOINROUND                   227
#define IDC_JOINMITER                   228
#define IDC_MITERLIMIT                  229
#define IDC_SEG1ON                      230
#define IDC_SEG1OFF                     231
#define IDC_OVERPRINT                   232
#define IDC_SEG2ON                      233
#define IDC_SEG2OFF                     234
#define IDC_SEG3ON                      235
#define IDC_SEG3OFF                     236
#define IDC_SEG4ON                      237
#define IDC_SEG4OFF                     238
#define IDC_CAPFLAT                     239
#define IDC_STOPPOSITION                1000
#define IDC_ADD                         1001
#define IDC_REMOVE                      1002
#define IDC_COMBOBOXEX1                 1003
#define IDC_GRADIENTBAR                 1003
#define IDC_COMBOBOXEX2                 1004
#define IDC_STOPPERHOLDER               1004
#define IDC_EDIT1                       1005
#define IDC_STOPCOLOR                   1005
#define IDC_BUTTON2                     1007
#define ID_PROPERTIES                   32771
#define ID_OPEN                         32772
#define ID_DUMMY_COMPILE                32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           1100
#endif
#endif
