#pragma once

#define WM_SUBMITUNDO     (WM_USER + 207)
#define WM_NEWGEOMDREW    (WM_USER + 208)
#define WM_ZOOMIN         (WM_USER + 209)
#define WM_ZOOMOUT        (WM_USER + 210)
#define WM_SPLITGEOM      (WM_USER + 211)
#define WM_PICKACTIVEGEOM (WM_USER + 212)
#define WM_PICKANCHOR     (WM_USER + 213)
#define WM_PICKGEOM       (WM_USER + 214)
#define WM_PICKBYRECT       (WM_USER + 215)
#define WM_PICKBYCIRCLE     (WM_USER + 216)
#define WM_PICKBYPOLY       (WM_USER + 217)
#define WM_LOOKUPGEOM       (WM_USER + 218)
#define WM_GETACTIVERECT    (WM_USER + 220)
#define WM_GETACTIVEAREA    (WM_USER + 221)
#define WM_TRANSFORM        (WM_USER + 222)
#define WM_TRANSFORMED      (WM_USER + 223)
#define WM_SETPRINTARECT    (WM_USER + 224)
#define WM_MOVEGEOM         (WM_USER + 225)

#define	WM_SETQUERYCOUNT    (WM_USER + 227)
#define WM_SELDRAWTOOL      (WM_USER + 230)
#define WM_PICKDATUM        (WM_USER + 231)
#define WM_NEWDATUM         (WM_USER + 232)
#define WM_MOVEDATUM        (WM_USER + 233)
#define WM_SELINFOTOOL      (WM_USER + 236)
#define WM_EXECOBJSQL       (WM_USER + 239)
#define WM_PICKLINK         (WM_USER + 241)
#define WM_SETROUTE         (WM_USER + 242)
#define WM_TRAFFICCLICK     (WM_USER + 243)
#define WM_SCROLLWINDOW     (WM_USER + 244)

#define WM_TOPO_PICK    (WM_USER + 245)
#define WM_TOPO_PICKBYPOLYGON (WM_USER + 246)
#define WM_TOPO_CROSS   (WM_USER + 248)
#define WM_TOPO_SPLIT   (WM_USER + 249)
#define WM_GEOMACTIVATED (WM_USER + 250)
#define WM_REMOVEGEOM	 (WM_USER + 251)
#define WM_CAPTUREIMAGE (WM_USER + 252)
