//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Viewer.rc

#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDS_DIRECTORYNOTFOUND           102
#define IDS_FILENOTFOUND                103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_GRFTYPE                     105
#define IDR_GISTYPE                     106
#define IDS_NOODBC                      107
#define IDS_WELCOMETOSUERS              108
#define IDS_NOTFOUNDFOLD                109
#define IDS_DATABASECANNOTOPEN          110
#define IDB_RIBBON_FILELARGE            111
#define IDS_ATLASFILENOTEXSIT           112
#define IDB_RIBBON_FILESMALL            113
#define IDS_NOODBCDNSACCESS             114
#define IDS_EXITCONFIRM                 115
#define IDS_MAPFILENOTEXSIT             116
#define IDS_FILECANNOTOPEN              117
#define IDS_LENGTHKM                    118
#define IDS_LENGTHM                     119
#define IDS_TOOLBAR_STANDARD            120
#define IDS_TOOLBAR_CUSTOMIZE           121
#define IDR_GEOM                        122
#define IDS_AREAKM                      123
#define IDS_AREAM                       124
#define IDS_DELETEGEOMLINK              125
#define IDR_VIEWERTYPE                  126
#define IDS_OLDVERSION                  127
#define IDR_MAINFRAME                   128
#define IDS_WINDOWS_MANAGER             129
#define IDS_FILECANNOTSAVE              130
#define IDS_NODATAFRONAVIGATION         131
#define IDS_LOGINSUCCEED                132
#define IDS_LOGINFAILD                  133
#define IDS_NOTSUPPORTGPS               134
#define IDS_OPTIMIZEDLENGTH             135
#define IDS_BEELENGTH                   136
#define IDR_LINKBAR                     137
#define IDS_NOACTIVELAYER               138
#define IDR_QUERYBAR                    139
#define IDS_SELECTPRINTZOOM             140
#define IDR_MEASUREBAR                  141
#define IDS_WRONGPWD                    142
#define IDS_FRAMETITLE                  143
#define IDR_NAVIGATEBAR                 144
#define IDR_INFOBAR                     145
#define IDB_RECMARK                     146
#define IDC_UP                          147
#define IDC_DOWN                        148
#define IDC_RIGHT                       149
#define IDC_LEFT                        150
#define IDC_LEFTUP                      151
#define IDC_RIGHTUP                     152
#define IDC_RIGHTDOWN                   153
#define IDC_LEFTDOWN                    154
#define IDB_RIBBON_MAIN                 155
#define IDB_BMPICONS                    156
#define IDB_MAP_LARGE                   157
#define IDB_MAP_SMALL                   158
#define IDB_GPS_LARGE                   159
#define IDC_POITYPECOMBO1               160
#define IDC_POITYPECOMBO2               161
#define IDC_POITYPECOMBO3               162
#define IDD_POIBAR                      163
#define IDP_FAILED_TO_CREATE            164
#define IDR_GRFTYPE_CNTR_IP             165
#define IDR_GISTYPE_CNTR_IP             166
#define IDR_GEOTYPE_CNTR_IP             167
#define IDR_BLKTYPE_CNTR_IP             168
#define IDS_PIRATIC                     169
#define ID_MAP_LEVELSLIDER              32770
#define ID_MAP_SCALESLIDER              32771
#define ID_TOOL_REGION                  32772
#define ID_COORDINATE_LONGITUDE         32773
#define ID_COORDINATE_LATITUDE          32774
#define ID_COORDINATE_LABLE1            32775
#define ID_COORDINATE_LABEL2            32776
#define ID_PANE_TABLE                   32777
#define ID_PANE_LAYER                   32778
#define ID_PANE_THEME                   32779
#define ID_PANE_PROPERTY                32780
#define ID_PANE_QUERY                   32781
#define ID_PANE_NAVIGATE                32782
#define ID_PANE_ATLAS                   32783
#define ID_PANE_VEHICLE                 32784
#define ID_MAP_LEVELEDIT                32785
#define ID_MAP_LEVELGO                  32786
#define ID_MAP_SCALEEDIT                32787
#define ID_MAP_SCALEGO                  32788
#define ID_PANE_POU                     32789
#define ID_PANE_CHANNEL                 32790
#define ID_INFORMATION_POI              32791
#define ID_INFO_POI1                    32792
#define ID_INFO_POI2                    32793
#define ID_INFO_POI3                    32794
#define ID_TOOL_INFO                    32795
#define ID_TOOL_LENGTH                  32796
#define ID_TOOL_AREA                    32797
#define ID_VIEW_MANAGER                 32798
#define ID_GPS_TRACE                    32799
#define ID_GPS_DEVICE                   32800
#define ID_TOOL_ZOOMIN                  32801
#define ID_TOOL_ZOOMOUT                 32802
#define ID_TOOL_PRINT                   32803
#define ID_TOOL_LINK                    32804
#define ID_GO_BACK                      32805
#define ID_GO_FORWARD                   32806
#define ID_GO_HOME                      32807
#define ID_TOOL_RADIUS                  32808
#define ID_TOOL_BOUND                   32809
#define ID_GEOM_LENGTH                  32810
#define ID_GEOM_AREA                    32811
#define ID_VIEW_RULER                   32812
#define ID_TOOL_PAN                     32813
#define ID_VIEW_LEGEND                  32814
#define ID_GPS_REPLAY                   32815
#define ID_TOOL_ROUTE                   32816
#define ID_TOOL_MARQUEE                 32817
#define ID_TOOL_DISPATCH                32818
#define ID_TRAFFIC_ROUTE                32819

// Next default values for new objects

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           1100
#endif
#endif
