// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "stdafx.h"
#include "column.h"

// Dispatch interfaces referenced by this interface
#include "StyleDisp.h"
#include "Font.h"
#include "valueitems.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CColumn properties

long CColumn::GetAlignment() const
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetAlignment(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

BOOL CColumn::GetAllowSizing() const
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetAllowSizing(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CColumn::GetHeaderDivider() const
{
	BOOL result;
	GetProperty(0x47, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetHeaderDivider(BOOL propVal)
{
	SetProperty(0x47, VT_BOOL, propVal);
}

BOOL CColumn::GetFooterDivider() const
{
	BOOL result;
	GetProperty(0x48, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetFooterDivider(BOOL propVal)
{
	SetProperty(0x48, VT_BOOL, propVal);
}

unsigned long CColumn::GetBackColor() const
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetBackColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

long CColumn::GetDividerStyle() const
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetDividerStyle(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

unsigned long CColumn::GetDividerColor() const
{
	unsigned long result;
	GetProperty(0x51, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetDividerColor(unsigned long propVal)
{
	SetProperty(0x51, VT_I4, propVal);
}

CString CColumn::GetCaption() const
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CColumn::SetCaption(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

CString CColumn::GetFooterText() const
{
	CString result;
	GetProperty(0x3a, VT_BSTR, (void*)&result);
	return result;
}

void CColumn::SetFooterText(LPCTSTR propVal)
{
	SetProperty(0x3a, VT_BSTR, propVal);
}

BOOL CColumn::GetDataChanged() const
{
	BOOL result;
	GetProperty(0x23, VT_BOOL, (void*)&result);
	return result;
}

CString CColumn::GetDataField() const
{
	CString result;
	GetProperty(0x8, VT_BSTR, (void*)&result);
	return result;
}

void CColumn::SetDataField(LPCTSTR propVal)
{
	SetProperty(0x8, VT_BSTR, propVal);
}

long CColumn::GetDataWidth() const
{
	long result;
	GetProperty(0x24, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetDataWidth(long propVal)
{
	SetProperty(0x24, VT_I4, propVal);
}

VARIANT CColumn::GetDefaultValue() const
{
	VARIANT result;
	GetProperty(0x9, VT_VARIANT, (void*)&result);
	return result;
}

void CColumn::SetDefaultValue(const VARIANT& propVal)
{
	SetProperty(0x9, VT_VARIANT, &propVal);
}

unsigned long CColumn::GetEditBackColor() const
{
	unsigned long result;
	GetProperty(0x21, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetEditBackColor(unsigned long propVal)
{
	SetProperty(0x21, VT_I4, propVal);
}

unsigned long CColumn::GetEditForeColor() const
{
	unsigned long result;
	GetProperty(0x22, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetEditForeColor(unsigned long propVal)
{
	SetProperty(0x22, VT_I4, propVal);
}

unsigned long CColumn::GetForeColor() const
{
	unsigned long result;
	GetProperty(0xa, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetForeColor(unsigned long propVal)
{
	SetProperty(0xa, VT_I4, propVal);
}

long CColumn::GetHeadAlignment() const
{
	long result;
	GetProperty(0x2a, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetHeadAlignment(long propVal)
{
	SetProperty(0x2a, VT_I4, propVal);
}

unsigned long CColumn::GetHeadBackColor() const
{
	unsigned long result;
	GetProperty(0xb, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetHeadBackColor(unsigned long propVal)
{
	SetProperty(0xb, VT_I4, propVal);
}

unsigned long CColumn::GetHeadForeColor() const
{
	unsigned long result;
	GetProperty(0xc, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetHeadForeColor(unsigned long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

long CColumn::GetFooterAlignment() const
{
	long result;
	GetProperty(0x3f, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetFooterAlignment(long propVal)
{
	SetProperty(0x3f, VT_I4, propVal);
}

unsigned long CColumn::GetFooterBackColor() const
{
	unsigned long result;
	GetProperty(0x3b, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetFooterBackColor(unsigned long propVal)
{
	SetProperty(0x3b, VT_I4, propVal);
}

unsigned long CColumn::GetFooterForeColor() const
{
	unsigned long result;
	GetProperty(0x3c, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetFooterForeColor(unsigned long propVal)
{
	SetProperty(0x3c, VT_I4, propVal);
}

short CColumn::GetColIndex() const
{
	short result;
	GetProperty(0xe, VT_I2, (void*)&result);
	return result;
}

float CColumn::GetLeft() const
{
	float result;
	GetProperty(0xf, VT_R4, (void*)&result);
	return result;
}

BOOL CColumn::GetLocked() const
{
	BOOL result;
	GetProperty(0x10, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetLocked(BOOL propVal)
{
	SetProperty(0x10, VT_BOOL, propVal);
}

CString CColumn::GetNumberFormat() const
{
	CString result;
	GetProperty(0x11, VT_BSTR, (void*)&result);
	return result;
}

void CColumn::SetNumberFormat(LPCTSTR propVal)
{
	SetProperty(0x11, VT_BSTR, propVal);
}

CString CColumn::GetText() const
{
	CString result;
	GetProperty(0x0, VT_BSTR, (void*)&result);
	return result;
}

void CColumn::SetText(LPCTSTR propVal)
{
	SetProperty(0x0, VT_BSTR, propVal);
}

float CColumn::GetTop() const
{
	float result;
	GetProperty(0x14, VT_R4, (void*)&result);
	return result;
}

VARIANT CColumn::GetValue() const
{
	VARIANT result;
	GetProperty(0x15, VT_VARIANT, (void*)&result);
	return result;
}

void CColumn::SetValue(const VARIANT& propVal)
{
	SetProperty(0x15, VT_VARIANT, &propVal);
}

BOOL CColumn::GetVisible() const
{
	BOOL result;
	GetProperty(0x16, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetVisible(BOOL propVal)
{
	SetProperty(0x16, VT_BOOL, propVal);
}

float CColumn::GetWidth() const
{
	float result;
	GetProperty(0x17, VT_R4, (void*)&result);
	return result;
}

void CColumn::SetWidth(float propVal)
{
	SetProperty(0x17, VT_R4, propVal);
}

BOOL CColumn::GetWrapText() const
{
	BOOL result;
	GetProperty(0x25, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetWrapText(BOOL propVal)
{
	SetProperty(0x25, VT_BOOL, propVal);
}

BOOL CColumn::GetButton() const
{
	BOOL result;
	GetProperty(0x28, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetButton(BOOL propVal)
{
	SetProperty(0x28, VT_BOOL, propVal);
}

long CColumn::GetMerge() const
{
	long result;
	GetProperty(0x33, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetMerge(long propVal)
{
	SetProperty(0x33, VT_I4, propVal);
}

long CColumn::GetFetchStyle() const
{
	long result;
	GetProperty(0x29, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetFetchStyle(long propVal)
{
	SetProperty(0x29, VT_I4, propVal);
}

CStyleDisp CColumn::GetStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x1d, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CColumn::SetStyle(LPDISPATCH propVal)
{
	SetProperty(0x1d, VT_DISPATCH, propVal);
}

CStyleDisp CColumn::GetHeadingStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x1e, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CColumn::SetHeadingStyle(LPDISPATCH propVal)
{
	SetProperty(0x1e, VT_DISPATCH, propVal);
}

CStyleDisp CColumn::GetFooterStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x3d, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CColumn::SetFooterStyle(LPDISPATCH propVal)
{
	SetProperty(0x3d, VT_DISPATCH, propVal);
}

CStyleDisp CColumn::GetEditorStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x1f, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CColumn::SetEditorStyle(LPDISPATCH propVal)
{
	SetProperty(0x1f, VT_DISPATCH, propVal);
}

COleFont CColumn::GetFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x1c, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CColumn::SetFont(LPDISPATCH propVal)
{
	SetProperty(0x1c, VT_DISPATCH, propVal);
}

COleFont CColumn::GetHeadFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x20, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CColumn::SetHeadFont(LPDISPATCH propVal)
{
	SetProperty(0x20, VT_DISPATCH, propVal);
}

COleFont CColumn::GetFooterFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x3e, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CColumn::SetFooterFont(LPDISPATCH propVal)
{
	SetProperty(0x3e, VT_DISPATCH, propVal);
}

short CColumn::GetOrder() const
{
	short result;
	GetProperty(0x2b, VT_I2, (void*)&result);
	return result;
}

void CColumn::SetOrder(short propVal)
{
	SetProperty(0x2b, VT_I2, propVal);
}

CString CColumn::GetEditMask() const
{
	CString result;
	GetProperty(0x2c, VT_BSTR, (void*)&result);
	return result;
}

void CColumn::SetEditMask(LPCTSTR propVal)
{
	SetProperty(0x2c, VT_BSTR, propVal);
}

BOOL CColumn::GetEditMaskUpdate() const
{
	BOOL result;
	GetProperty(0x2d, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetEditMaskUpdate(BOOL propVal)
{
	SetProperty(0x2d, VT_BOOL, propVal);
}

BOOL CColumn::GetEditMaskRight() const
{
	BOOL result;
	GetProperty(0x44, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetEditMaskRight(BOOL propVal)
{
	SetProperty(0x44, VT_BOOL, propVal);
}

VARIANT CColumn::GetDropDown() const
{
	VARIANT result;
	GetProperty(0x2f, VT_VARIANT, (void*)&result);
	return result;
}

void CColumn::SetDropDown(const VARIANT& propVal)
{
	SetProperty(0x2f, VT_VARIANT, &propVal);
}

VARIANT CColumn::GetExternalEditor() const
{
	VARIANT result;
	GetProperty(0x46, VT_VARIANT, (void*)&result);
	return result;
}

void CColumn::SetExternalEditor(const VARIANT& propVal)
{
	SetProperty(0x46, VT_VARIANT, &propVal);
}

float CColumn::GetCellTop() const
{
	float result;
	GetProperty(0x30, VT_R4, (void*)&result);
	return result;
}

VARIANT CColumn::GetButtonPicture() const
{
	VARIANT result;
	GetProperty(0x31, VT_VARIANT, (void*)&result);
	return result;
}

void CColumn::SetButtonPicture(const VARIANT& propVal)
{
	SetProperty(0x31, VT_VARIANT, &propVal);
}

BOOL CColumn::GetAllowFocus() const
{
	BOOL result;
	GetProperty(0x32, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetAllowFocus(BOOL propVal)
{
	SetProperty(0x32, VT_BOOL, propVal);
}

BOOL CColumn::GetButtonText() const
{
	BOOL result;
	GetProperty(0x34, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetButtonText(BOOL propVal)
{
	SetProperty(0x34, VT_BOOL, propVal);
}

BOOL CColumn::GetButtonAlways() const
{
	BOOL result;
	GetProperty(0x35, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetButtonAlways(BOOL propVal)
{
	SetProperty(0x35, VT_BOOL, propVal);
}

BOOL CColumn::GetButtonHeader() const
{
	BOOL result;
	GetProperty(0x40, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetButtonHeader(BOOL propVal)
{
	SetProperty(0x40, VT_BOOL, propVal);
}

BOOL CColumn::GetButtonFooter() const
{
	BOOL result;
	GetProperty(0x41, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetButtonFooter(BOOL propVal)
{
	SetProperty(0x41, VT_BOOL, propVal);
}

BOOL CColumn::GetOwnerDraw() const
{
	BOOL result;
	GetProperty(0x42, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetOwnerDraw(BOOL propVal)
{
	SetProperty(0x42, VT_BOOL, propVal);
}

BOOL CColumn::GetAutoDropDown() const
{
	BOOL result;
	GetProperty(0x43, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetAutoDropDown(BOOL propVal)
{
	SetProperty(0x43, VT_BOOL, propVal);
}

BOOL CColumn::GetDropDownList() const
{
	BOOL result;
	GetProperty(0x45, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetDropDownList(BOOL propVal)
{
	SetProperty(0x45, VT_BOOL, propVal);
}

BOOL CColumn::GetAutoCompletion() const
{
	BOOL result;
	GetProperty(0x50, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetAutoCompletion(BOOL propVal)
{
	SetProperty(0x50, VT_BOOL, propVal);
}

long CColumn::GetDisplayAlignment() const
{
	long result;
	GetProperty(0x49, VT_I4, (void*)&result);
	return result;
}

long CColumn::GetConvertEmptyCell() const
{
	long result;
	GetProperty(0x4c, VT_I4, (void*)&result);
	return result;
}

void CColumn::SetConvertEmptyCell(long propVal)
{
	SetProperty(0x4c, VT_I4, propVal);
}

CString CColumn::GetName() const
{
	CString result;
	GetProperty(0x4a, VT_BSTR, (void*)&result);
	return result;
}

CString CColumn::GetTableName() const
{
	CString result;
	GetProperty(0x4b, VT_BSTR, (void*)&result);
	return result;
}

BOOL CColumn::GetGroup() const
{
	BOOL result;
	GetProperty(0x4e, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetGroup(BOOL propVal)
{
	SetProperty(0x4e, VT_BOOL, propVal);
}

CString CColumn::GetFilterText() const
{
	CString result;
	GetProperty(0x52, VT_BSTR, (void*)&result);
	return result;
}

void CColumn::SetFilterText(LPCTSTR propVal)
{
	SetProperty(0x52, VT_BSTR, propVal);
}

VARIANT CColumn::GetFilterButtonPicture() const
{
	VARIANT result;
	GetProperty(0x53, VT_VARIANT, (void*)&result);
	return result;
}

void CColumn::SetFilterButtonPicture(const VARIANT& propVal)
{
	SetProperty(0x53, VT_VARIANT, &propVal);
}

BOOL CColumn::GetFilterButton() const
{
	BOOL result;
	GetProperty(0x54, VT_BOOL, (void*)&result);
	return result;
}

void CColumn::SetFilterButton(BOOL propVal)
{
	SetProperty(0x54, VT_BOOL, propVal);
}

VARIANT CColumn::GetTag() const
{
	VARIANT result;
	GetProperty(0x55, VT_VARIANT, (void*)&result);
	return result;
}

void CColumn::SetTag(const VARIANT& propVal)
{
	SetProperty(0x55, VT_VARIANT, &propVal);
}

float CColumn::GetMinWidth() const
{
	float result;
	GetProperty(0x56, VT_R4, (void*)&result);
	return result;
}

void CColumn::SetMinWidth(float propVal)
{
	SetProperty(0x56, VT_R4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CColumn operations

CValueItems CColumn::GetValueItems()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x18, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CValueItems(pDispatch);
}

CString CColumn::CellText(const VARIANT& Bookmark)
{
	CString result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		&Bookmark);
	return result;
}

VARIANT CColumn::CellValue(const VARIANT& Bookmark)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		&Bookmark);
	return result;
}

void CColumn::AddCellStyle(short Condition, const VARIANT& Style)
{
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition, &Style);
}

void CColumn::AddRegexCellStyle(short Condition, const VARIANT& Style, LPCTSTR Regex)
{
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT VTS_BSTR;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition, &Style, Regex);
}

void CColumn::ClearCellStyle(short Condition)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition);
}

void CColumn::ClearRegexCellStyle(short Condition, const VARIANT& Regex)
{
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition, &Regex);
}

void CColumn::Fix(BOOL Fix, short pos)
{
	static BYTE parms[] =
		VTS_BOOL VTS_I2;
	InvokeHelper(0x58, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Fix, pos);
}

void CColumn::Refresh()
{
	InvokeHelper(0x36, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CColumn::RefreshCell(const VARIANT& Bookmark)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x37, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Bookmark);
}

void CColumn::Refetch()
{
	InvokeHelper(0x38, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CColumn::RefetchCell(const VARIANT& Bookmark)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x39, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Bookmark);
}

void CColumn::AutoSize()
{
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}
