#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

// Dispatch interfaces referenced by this interface
class CStyleDisp;
class COleFont;
class CValueItems;

/////////////////////////////////////////////////////////////////////////////
// CColumn wrapper class

class __declspec(dllexport) CColumn : public COleDispatchDriver
{
public:
	CColumn()
	{
	} // Calls COleDispatchDriver default constructor
	CColumn(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	CColumn(const CColumn& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
public:
	long GetAlignment() const;
	void SetAlignment(long);
	BOOL GetAllowSizing() const;
	void SetAllowSizing(BOOL);
	BOOL GetHeaderDivider() const;
	void SetHeaderDivider(BOOL);
	BOOL GetFooterDivider() const;
	void SetFooterDivider(BOOL);
	unsigned long GetBackColor() const;
	void SetBackColor(unsigned long);
	long GetDividerStyle() const;
	void SetDividerStyle(long);
	unsigned long GetDividerColor() const;
	void SetDividerColor(unsigned long);
	CString GetCaption() const;
	void SetCaption(LPCTSTR);
	CString GetFooterText() const;
	void SetFooterText(LPCTSTR);
	BOOL GetDataChanged() const;
	CString GetDataField() const;
	void SetDataField(LPCTSTR);
	long GetDataWidth() const;
	void SetDataWidth(long);
	VARIANT GetDefaultValue() const;
	void SetDefaultValue(const VARIANT&);
	unsigned long GetEditBackColor() const;
	void SetEditBackColor(unsigned long);
	unsigned long GetEditForeColor() const;
	void SetEditForeColor(unsigned long);
	unsigned long GetForeColor() const;
	void SetForeColor(unsigned long);
	long GetHeadAlignment() const;
	void SetHeadAlignment(long);
	unsigned long GetHeadBackColor() const;
	void SetHeadBackColor(unsigned long);
	unsigned long GetHeadForeColor() const;
	void SetHeadForeColor(unsigned long);
	long GetFooterAlignment() const;
	void SetFooterAlignment(long);
	unsigned long GetFooterBackColor() const;
	void SetFooterBackColor(unsigned long);
	unsigned long GetFooterForeColor() const;
	void SetFooterForeColor(unsigned long);
	short GetColIndex() const;
	float GetLeft() const;
	BOOL GetLocked() const;
	void SetLocked(BOOL);
	CString GetNumberFormat() const;
	void SetNumberFormat(LPCTSTR);
	CString GetText() const;
	void SetText(LPCTSTR);
	float GetTop() const;
	VARIANT GetValue() const;
	void SetValue(const VARIANT&);
	BOOL GetVisible() const;
	void SetVisible(BOOL);
	float GetWidth() const;
	void SetWidth(float);
	BOOL GetWrapText() const;
	void SetWrapText(BOOL);
	BOOL GetButton() const;
	void SetButton(BOOL);
	long GetMerge() const;
	void SetMerge(long);
	long GetFetchStyle() const;
	void SetFetchStyle(long);
	CStyleDisp GetStyle() const;
	void SetStyle(LPDISPATCH);
	CStyleDisp GetHeadingStyle() const;
	void SetHeadingStyle(LPDISPATCH);
	CStyleDisp GetFooterStyle() const;
	void SetFooterStyle(LPDISPATCH);
	CStyleDisp GetEditorStyle() const;
	void SetEditorStyle(LPDISPATCH);
	COleFont GetFont() const;
	void SetFont(LPDISPATCH);
	COleFont GetHeadFont() const;
	void SetHeadFont(LPDISPATCH);
	COleFont GetFooterFont() const;
	void SetFooterFont(LPDISPATCH);
	short GetOrder() const;
	void SetOrder(short);
	CString GetEditMask() const;
	void SetEditMask(LPCTSTR);
	BOOL GetEditMaskUpdate() const;
	void SetEditMaskUpdate(BOOL);
	BOOL GetEditMaskRight() const;
	void SetEditMaskRight(BOOL);
	VARIANT GetDropDown() const;
	void SetDropDown(const VARIANT&);
	VARIANT GetExternalEditor() const;
	void SetExternalEditor(const VARIANT&);
	float GetCellTop() const;
	VARIANT GetButtonPicture() const;
	void SetButtonPicture(const VARIANT&);
	BOOL GetAllowFocus() const;
	void SetAllowFocus(BOOL);
	BOOL GetButtonText() const;
	void SetButtonText(BOOL);
	BOOL GetButtonAlways() const;
	void SetButtonAlways(BOOL);
	BOOL GetButtonHeader() const;
	void SetButtonHeader(BOOL);
	BOOL GetButtonFooter() const;
	void SetButtonFooter(BOOL);
	BOOL GetOwnerDraw() const;
	void SetOwnerDraw(BOOL);
	BOOL GetAutoDropDown() const;
	void SetAutoDropDown(BOOL);
	BOOL GetDropDownList() const;
	void SetDropDownList(BOOL);
	BOOL GetAutoCompletion() const;
	void SetAutoCompletion(BOOL);
	long GetDisplayAlignment() const;
	long GetConvertEmptyCell() const;
	void SetConvertEmptyCell(long);
	CString GetName() const;
	CString GetTableName() const;
	BOOL GetGroup() const;
	void SetGroup(BOOL);
	CString GetFilterText() const;
	void SetFilterText(LPCTSTR);
	VARIANT GetFilterButtonPicture() const;
	void SetFilterButtonPicture(const VARIANT&);
	BOOL GetFilterButton() const;
	void SetFilterButton(BOOL);
	VARIANT GetTag() const;
	void SetTag(const VARIANT&);
	float GetMinWidth() const;
	void SetMinWidth(float);

	// Operations
public:
	CValueItems GetValueItems();
	CString CellText(const VARIANT& Bookmark);
	VARIANT CellValue(const VARIANT& Bookmark);
	void AddCellStyle(short Condition, const VARIANT& Style);
	void AddRegexCellStyle(short Condition, const VARIANT& Style, LPCTSTR Regex);
	void ClearCellStyle(short Condition);
	void ClearRegexCellStyle(short Condition, const VARIANT& Regex);
	void Fix(BOOL Fix, short pos);
	void Refresh();
	void RefreshCell(const VARIANT& Bookmark);
	void Refetch();
	void RefetchCell(const VARIANT& Bookmark);
	void AutoSize();
};
