#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

// Dispatch interfaces referenced by this interface
class CColumn;

/////////////////////////////////////////////////////////////////////////////
// CColumns wrapper class

class __declspec(dllexport) CColumns : public COleDispatchDriver
{
public:
	CColumns()
	{
	} // Calls COleDispatchDriver default constructor
	CColumns(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	CColumns(const CColumns& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
public:
	long GetCount() const;

	// Operations
public:
	LPUNKNOWN Get_NewEnum();
	CColumn GetItem(const VARIANT& Index);
	CColumn Add(short Index);
	void Remove(const VARIANT& Index);
	void Clear();
};
