



#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CError;

/////////////////////////////////////////////////////////////////////////////
// CErrors wrapper class

class CErrors : public COleDispatchDriver
{
public:
	CErrors() {}		// Calls COleDispatchDriver default constructor
	CErrors(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CErrors(const CErrors& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();

// Operations
public:
	LPUNKNOWN Get_NewEnum();
	CError GetItem(const VARIANT& Index);
	void Clear();
};





