// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "error.h"


/////////////////////////////////////////////////////////////////////////////
// CError properties

long CError::GetNumber()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CError::SetNumber(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

long CError::GetNativeError()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CError::SetNativeError(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

CString CError::GetDescription()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CError::SetDescription(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CError::GetSource()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CError::SetSource(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

CString CError::GetHelpFile()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CError::SetHelpFile(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

long CError::GetHelpContext()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CError::SetHelpContext(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

CString CError::GetSQLState()
{
	CString result;
	GetProperty(0x7, VT_BSTR, (void*)&result);
	return result;
}

void CError::SetSQLState(LPCTSTR propVal)
{
	SetProperty(0x7, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CError operations
