



#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CError wrapper class

class CError : public COleDispatchDriver
{
public:
	CError() {}		// Calls COleDispatchDriver default constructor
	CError(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CError(const CError& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetNumber();
	void SetNumber(long);
	long GetNativeError();
	void SetNativeError(long);
	CString GetDescription();
	void SetDescription(LPCTSTR);
	CString GetSource();
	void SetSource(LPCTSTR);
	CString GetHelpFile();
	void SetHelpFile(LPCTSTR);
	long GetHelpContext();
	void SetHelpContext(long);
	CString GetSQLState();
	void SetSQLState(LPCTSTR);

// Operations
public:
};





