// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// COleFont wrapper class

class COleFont : public COleDispatchDriver
{
public:
	COleFont()
	{
	} // Calls COleDispatchDriver default constructor
	COleFont(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	COleFont(const COleFont& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
public:
	CString GetName() const;
	void SetName(LPCTSTR);
	CY GetSize() const;
	void SetSize(const CY&);
	BOOL GetBold() const;
	void SetBold(BOOL);
	BOOL GetItalic() const;
	void SetItalic(BOOL);
	BOOL GetUnderline() const;
	void SetUnderline(BOOL);
	BOOL GetStrikethrough() const;
	void SetStrikethrough(BOOL);
	short GetWeight() const;
	void SetWeight(short);
	short GetCharset() const;
	void SetCharset(short);

	// Operations
public:
};
