// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "groupcolumns.h"

// Dispatch interfaces referenced by this interface
#include "column.h"


/////////////////////////////////////////////////////////////////////////////
// CGroupColumns properties

long CGroupColumns::GetCount()
{
	long result;
	GetProperty(0x7d2, VT_I4, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CGroupColumns operations

LPUNKNOWN CGroupColumns::Get_NewEnum()
{
	LPUNKNOWN result;
	InvokeHelper(0xfffffffc, DISPATCH_PROPERTYGET, VT_UNKNOWN, (void*)&result, nullptr);
	return result;
}

CColumn CGroupColumns::GetItem(const VARIANT& Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		&Index);
	return CColumn(pDispatch);
}

CColumn CGroupColumns::Add(short Index, const VARIANT& Col)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT;
	InvokeHelper(0x7d5, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Index, &Col);
	return CColumn(pDispatch);
}

void CGroupColumns::Remove(const VARIANT& Index)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x7d6, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		 &Index);
}
