



#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CColumn;

/////////////////////////////////////////////////////////////////////////////
// CGroupColumns wrapper class

class CGroupColumns : public COleDispatchDriver
{
public:
	CGroupColumns() {}		// Calls COleDispatchDriver default constructor
	CGroupColumns(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGroupColumns(const CGroupColumns& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();

// Operations
public:
	LPUNKNOWN Get_NewEnum();
	CColumn GetItem(const VARIANT& Index);
	CColumn Add(short Index, const VARIANT& Col);
	void Remove(const VARIANT& Index);
};





