#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLayouts wrapper class

class CLayouts : public COleDispatchDriver
{
	public:
	CLayouts()
	{
	} // Calls COleDispatchDriver default constructor
	CLayouts(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	CLayouts(const CLayouts& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
	public:
	long GetCount() const;

	// Operations
	public:
	LPUNKNOWN Get_NewEnum();
	VARIANT GetItem(const VARIANT& Index);
	void Add(const VARIANT& LayoutName);
	void Remove(const VARIANT& Index);
};
