#pragma once

#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMsDgridCtrl wrapper class

class __declspec(dllexport) CMsDgridCtrl : public CWnd
{
	protected:
	DECLARE_DYNCREATE(CMsDgridCtrl)
	public:
	static CLSID const& GetClsid()
	{
		static CLSID const clsid
				= {0x28c00, 0x0, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x46}};
		return clsid;
	}

	BOOL Create(LPCTSTR lpszClassName,
	                    LPCTSTR lpszWindowName, DWORD dwStyle,
	                    const RECT& rect,
	                    CWnd* pParentWnd, UINT nId,
	                    CCreateContext* pContext = nullptr) override
	{
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nId);
	}

	BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
	            const RECT& rect, CWnd* pParentWnd, UINT nId,
	            CFile* pPersist = nullptr, BOOL bStorage = FALSE,
	            BSTR bstrLicKey = nullptr)
	{
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nId,
		                     pPersist, bStorage, bstrLicKey);
	}

	// Attributes
	public:
	BOOL GetAllowDelete() const;
	void SetAllowDelete(BOOL);
	BOOL GetAllowAddNew() const;
	void SetAllowAddNew(BOOL);
	BOOL GetAllowRowSizing() const;
	void SetAllowRowSizing(BOOL);
	BOOL GetAllowUpdate() const;
	void SetAllowUpdate(BOOL);
	short GetAppearance() const;
	void SetAppearance(short);
	short GetBorderStyle() const;
	void SetBorderStyle(short);
	VARIANT GetBookmark() const;
	void SetBookmark(const VARIANT&);
	short GetCol() const;
	void SetCol(short);
	BOOL GetColumnHeaders() const;
	void SetColumnHeaders(BOOL);
	BOOL GetCurrentCellVisible() const;
	void SetCurrentCellVisible(BOOL);
	BOOL GetCurrentCellModified() const;
	void SetCurrentCellModified(BOOL);
	BOOL GetDataChanged() const;
	void SetDataChanged(BOOL);
	long GetDataMode() const;
	void SetDataMode(long);
	LPUNKNOWN GetDataSource() const;
	void SetDataSource(LPUNKNOWN);
	float GetDefColWidth() const;
	void SetDefColWidth(float);
	BOOL GetEditActive() const;
	void SetEditActive(BOOL);
	BOOL GetEnabled() const;
	void SetEnabled(BOOL);
	VARIANT GetFirstRow() const;
	void SetFirstRow(const VARIANT&);
	LPDISPATCH GetHeadFont() const;
	void SetHeadFont(LPDISPATCH);
	float GetHeadLines() const;
	void SetHeadLines(float);
	OLE_HANDLE GetHWnd() const;
	long GetHWndEditor() const;
	BOOL GetMarqueeUnique() const;
	void SetMarqueeUnique(BOOL);
	long GetMarqueeStyle() const;
	void SetMarqueeStyle(long);
	BOOL GetRecordSelectors() const;
	void SetRecordSelectors(BOOL);
	short GetRow() const;
	void SetRow(short);
	long GetRowDividerStyle() const;
	void SetRowDividerStyle(long);
	float GetRowHeight() const;
	void SetRowHeight(float);
	long GetScrollBars() const;
	void SetScrollBars(long);
	long GetSelLength() const;
	void SetSelLength(long);
	long GetSelStart() const;
	void SetSelStart(long);
	CString GetSelText() const;
	void SetSelText(LPCTSTR);
	short GetSelStartCol() const;
	void SetSelStartCol(short);
	short GetSelEndCol() const;
	void SetSelEndCol(short);
	short GetSplit() const;
	void SetSplit(short);
	short GetVisibleCols() const;
	short GetVisibleRows() const;
	OLE_COLOR GetBackColor() const;
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor() const;
	void SetForeColor(OLE_COLOR);
	CString GetCaption() const;
	void SetCaption(LPCTSTR);
	LPFONTDISP GetFont() const;
	void SetFont(LPFONTDISP);
	short GetLeftCol() const;
	void SetLeftCol(short);
	BOOL GetAllowArrows() const;
	void SetAllowArrows(BOOL);
	BOOL GetTabAcrossSplits() const;
	void SetTabAcrossSplits(BOOL);
	long GetTabAction() const;
	void SetTabAction(long);
	BOOL GetWrapCellPointer() const;
	void SetWrapCellPointer(BOOL);
	long GetApproxCount() const;
	void SetApproxCount(long);
	CString GetErrorText() const;
	long GetAddNewMode() const;
	CString GetText() const;
	void SetText(LPCTSTR);

	// Operations
	public:
	void AboutBox();
	LPDISPATCH GetColumn(const VARIANT& Index);
	LPDISPATCH GetColumns();

	LPDISPATCH GetSplits(const VARIANT& Index);
	VARIANT GetSelBookmarks(const VARIANT& Index);
	short ColContaining(float X);
	VARIANT GetBookmark(long RowNum);
	void ReBind();
	VARIANT RowBookmark(short RowNum);
	short RowContaining(float Y);
	float RowTop(short RowNum);
	void Scroll(long Cols, long Rows);
	void Refresh();
	LPDISPATCH CaptureImage();
	void ClearSelCols();
	void ClearFields();
	void HoldFields();
	short SplitContaining(float X, float Y);
};
