#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPicture wrapper class

class CPicture : public COleDispatchDriver
{
	public:
	CPicture()
	{
	} // Calls COleDispatchDriver default constructor
	CPicture(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	CPicture(const CPicture& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
	public:
	long GetHandle() const;
	long GetHPal() const;
	void SetHPal(long);
	short GetType() const;
	long GetWidth() const;
	long GetHeight() const;

	// Operations
	public:
	// method 'Render' not emitted because of invalid return type or parameter type
};
