#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

// Dispatch interfaces referenced by this interface
class CPrintInfo1;

/////////////////////////////////////////////////////////////////////////////
// CPrintInfos wrapper class

class CPrintInfos : public COleDispatchDriver
{
	public:
	CPrintInfos()
	{
	} // Calls COleDispatchDriver default constructor
	CPrintInfos(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	CPrintInfos(const CPrintInfos& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
	public:
	long GetCount() const;

	// Operations
	public:
	LPUNKNOWN Get_NewEnum();
	CPrintInfo1 GetItem(const VARIANT& Index);
	CPrintInfo1 Add(LPCTSTR Name);
	void Remove(const VARIANT& Index);
	void Clear();
};
