#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CPrintInfo1 wrapper class

class CPrintInfo1 : public COleDispatchDriver
{
	public:
	CPrintInfo1()
	{
	} // Calls COleDispatchDriver default constructor
	CPrintInfo1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	CPrintInfo1(const CPrintInfo1& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
	public:
	CString GetName() const;
	void SetName(LPCTSTR);
	CString GetPageHeader() const;
	void SetPageHeader(LPCTSTR);
	CString GetPageFooter() const;
	void SetPageFooter(LPCTSTR);
	COleFont GetPageHeaderFont() const;
	void SetPageHeaderFont(LPDISPATCH);
	COleFont GetPageFooterFont() const;
	void SetPageFooterFont(LPDISPATCH);
	BOOL GetDraft() const;
	void SetDraft(BOOL);
	BOOL GetDefault() const;
	void SetDefault(BOOL);
	BOOL GetRepeatGridHeader() const;
	void SetRepeatGridHeader(BOOL);
	BOOL GetRepeatSplitHeaders() const;
	void SetRepeatSplitHeaders(BOOL);
	BOOL GetRepeatColumnHeaders() const;
	void SetRepeatColumnHeaders(BOOL);
	BOOL GetRepeatColumnFooters() const;
	void SetRepeatColumnFooters(BOOL);
	BOOL GetVariableRowHeight() const;
	void SetVariableRowHeight(BOOL);
	short GetNumberOfCopies() const;
	void SetNumberOfCopies(short);
	BOOL GetCollate() const;
	void SetCollate(BOOL);
	CString GetPreviewCaption() const;
	void SetPreviewCaption(LPCTSTR);
	CString GetPreviewPageOf() const;
	void SetPreviewPageOf(LPCTSTR);
	BOOL GetPreviewMaximize() const;
	void SetPreviewMaximize(BOOL);
	BOOL GetPageSetupCancelled() const;
	void SetPageSetupCancelled(BOOL);
	BOOL GetNoClipping() const;
	void SetNoClipping(BOOL);
	long GetPageHeaderHeight() const;
	void SetPageHeaderHeight(long);
	long GetPageFooterHeight() const;
	void SetPageFooterHeight(long);
	BOOL GetPageHeaderOwnerDraw() const;
	void SetPageHeaderOwnerDraw(BOOL);
	BOOL GetPageFooterOwnerDraw() const;
	void SetPageFooterOwnerDraw(BOOL);
	BOOL GetNeedTotalPageCount() const;
	void SetNeedTotalPageCount(BOOL);
	CString GetRangeOfPages() const;
	void SetRangeOfPages(LPCTSTR);
	VARIANT GetSettings() const;
	void SetSettings(const VARIANT&);
	CString GetSettingsDeviceName() const;
	void SetSettingsDeviceName(LPCTSTR);
	short GetSettingsOrientation() const;
	void SetSettingsOrientation(short);
	long GetSettingsMarginLeft() const;
	void SetSettingsMarginLeft(long);
	long GetSettingsMarginTop() const;
	void SetSettingsMarginTop(long);
	long GetSettingsMarginRight() const;
	void SetSettingsMarginRight(long);
	long GetSettingsMarginBottom() const;
	void SetSettingsMarginBottom(long);
	short GetSettingsPaperSize() const;
	void SetSettingsPaperSize(short);
	long GetSettingsPaperWidth() const;
	void SetSettingsPaperWidth(long);
	long GetSettingsPaperHeight() const;
	void SetSettingsPaperHeight(long);
	short GetSettingsPaperBin() const;
	void SetSettingsPaperBin(short);
	long GetUnitsPerInch() const;
	void SetUnitsPerInch(long);
	BOOL GetPreviewAllowFileOps() const;
	void SetPreviewAllowFileOps(BOOL);
	long GetPreviewInitZoom() const;
	void SetPreviewInitZoom(long);
	long GetPreviewInitPosX() const;
	void SetPreviewInitPosX(long);
	long GetPreviewInitPosY() const;
	void SetPreviewInitPosY(long);
	long GetPreviewInitWidth() const;
	void SetPreviewInitWidth(long);
	long GetPreviewInitHeight() const;
	void SetPreviewInitHeight(long);
	long GetPreviewInitScreenFill() const;
	void SetPreviewInitScreenFill(long);

	// Operations
	public:
	void PrintData(const VARIANT& selector);
	void PrintPreview(const VARIANT& selector);
	void PageSetup();
	void SetMenuText(long Index, LPCTSTR Text);
	CString GetMenuText(long Index);
	void SubstituteFont(LPCTSTR UnavailableFont, const VARIANT& AvailableFont);
	CString GetSubstituteFont(LPCTSTR UnavailableFont);
};
