// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "stdafx.h"
#include "printinfo.h"

// Dispatch interfaces referenced by this interface
#include "font.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CPrintInfo1 properties

CString CPrintInfo1::GetName() const
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CPrintInfo1::SetName(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CPrintInfo1::GetPageHeader() const
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CPrintInfo1::SetPageHeader(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CPrintInfo1::GetPageFooter() const
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CPrintInfo1::SetPageFooter(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

COleFont CPrintInfo1::GetPageHeaderFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x4, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CPrintInfo1::SetPageHeaderFont(LPDISPATCH propVal)
{
	SetProperty(0x4, VT_DISPATCH, propVal);
}

COleFont CPrintInfo1::GetPageFooterFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x5, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CPrintInfo1::SetPageFooterFont(LPDISPATCH propVal)
{
	SetProperty(0x5, VT_DISPATCH, propVal);
}

BOOL CPrintInfo1::GetDraft() const
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetDraft(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CPrintInfo1::GetDefault() const
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetDefault(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CPrintInfo1::GetRepeatGridHeader() const
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetRepeatGridHeader(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CPrintInfo1::GetRepeatSplitHeaders() const
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetRepeatSplitHeaders(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

BOOL CPrintInfo1::GetRepeatColumnHeaders() const
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetRepeatColumnHeaders(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

BOOL CPrintInfo1::GetRepeatColumnFooters() const
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetRepeatColumnFooters(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

BOOL CPrintInfo1::GetVariableRowHeight() const
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetVariableRowHeight(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

short CPrintInfo1::GetNumberOfCopies() const
{
	short result;
	GetProperty(0xd, VT_I2, (void*)&result);
	return result;
}

void CPrintInfo1::SetNumberOfCopies(short propVal)
{
	SetProperty(0xd, VT_I2, propVal);
}

BOOL CPrintInfo1::GetCollate() const
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetCollate(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}

CString CPrintInfo1::GetPreviewCaption() const
{
	CString result;
	GetProperty(0xf, VT_BSTR, (void*)&result);
	return result;
}

void CPrintInfo1::SetPreviewCaption(LPCTSTR propVal)
{
	SetProperty(0xf, VT_BSTR, propVal);
}

CString CPrintInfo1::GetPreviewPageOf() const
{
	CString result;
	GetProperty(0x10, VT_BSTR, (void*)&result);
	return result;
}

void CPrintInfo1::SetPreviewPageOf(LPCTSTR propVal)
{
	SetProperty(0x10, VT_BSTR, propVal);
}

BOOL CPrintInfo1::GetPreviewMaximize() const
{
	BOOL result;
	GetProperty(0x11, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetPreviewMaximize(BOOL propVal)
{
	SetProperty(0x11, VT_BOOL, propVal);
}

BOOL CPrintInfo1::GetPageSetupCancelled() const
{
	BOOL result;
	GetProperty(0x2b, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetPageSetupCancelled(BOOL propVal)
{
	SetProperty(0x2b, VT_BOOL, propVal);
}

BOOL CPrintInfo1::GetNoClipping() const
{
	BOOL result;
	GetProperty(0x2c, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetNoClipping(BOOL propVal)
{
	SetProperty(0x2c, VT_BOOL, propVal);
}

long CPrintInfo1::GetPageHeaderHeight() const
{
	long result;
	GetProperty(0x26, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetPageHeaderHeight(long propVal)
{
	SetProperty(0x26, VT_I4, propVal);
}

long CPrintInfo1::GetPageFooterHeight() const
{
	long result;
	GetProperty(0x27, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetPageFooterHeight(long propVal)
{
	SetProperty(0x27, VT_I4, propVal);
}

BOOL CPrintInfo1::GetPageHeaderOwnerDraw() const
{
	BOOL result;
	GetProperty(0x28, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetPageHeaderOwnerDraw(BOOL propVal)
{
	SetProperty(0x28, VT_BOOL, propVal);
}

BOOL CPrintInfo1::GetPageFooterOwnerDraw() const
{
	BOOL result;
	GetProperty(0x29, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetPageFooterOwnerDraw(BOOL propVal)
{
	SetProperty(0x29, VT_BOOL, propVal);
}

BOOL CPrintInfo1::GetNeedTotalPageCount() const
{
	BOOL result;
	GetProperty(0x2a, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetNeedTotalPageCount(BOOL propVal)
{
	SetProperty(0x2a, VT_BOOL, propVal);
}

CString CPrintInfo1::GetRangeOfPages() const
{
	CString result;
	GetProperty(0x17, VT_BSTR, (void*)&result);
	return result;
}

void CPrintInfo1::SetRangeOfPages(LPCTSTR propVal)
{
	SetProperty(0x17, VT_BSTR, propVal);
}

VARIANT CPrintInfo1::GetSettings() const
{
	VARIANT result;
	GetProperty(0x19, VT_VARIANT, (void*)&result);
	return result;
}

void CPrintInfo1::SetSettings(const VARIANT& propVal)
{
	SetProperty(0x19, VT_VARIANT, &propVal);
}

CString CPrintInfo1::GetSettingsDeviceName() const
{
	CString result;
	GetProperty(0x1c, VT_BSTR, (void*)&result);
	return result;
}

void CPrintInfo1::SetSettingsDeviceName(LPCTSTR propVal)
{
	SetProperty(0x1c, VT_BSTR, propVal);
}

short CPrintInfo1::GetSettingsOrientation() const
{
	short result;
	GetProperty(0x1d, VT_I2, (void*)&result);
	return result;
}

void CPrintInfo1::SetSettingsOrientation(short propVal)
{
	SetProperty(0x1d, VT_I2, propVal);
}

long CPrintInfo1::GetSettingsMarginLeft() const
{
	long result;
	GetProperty(0x1e, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetSettingsMarginLeft(long propVal)
{
	SetProperty(0x1e, VT_I4, propVal);
}

long CPrintInfo1::GetSettingsMarginTop() const
{
	long result;
	GetProperty(0x1f, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetSettingsMarginTop(long propVal)
{
	SetProperty(0x1f, VT_I4, propVal);
}

long CPrintInfo1::GetSettingsMarginRight() const
{
	long result;
	GetProperty(0x20, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetSettingsMarginRight(long propVal)
{
	SetProperty(0x20, VT_I4, propVal);
}

long CPrintInfo1::GetSettingsMarginBottom() const
{
	long result;
	GetProperty(0x21, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetSettingsMarginBottom(long propVal)
{
	SetProperty(0x21, VT_I4, propVal);
}

short CPrintInfo1::GetSettingsPaperSize() const
{
	short result;
	GetProperty(0x22, VT_I2, (void*)&result);
	return result;
}

void CPrintInfo1::SetSettingsPaperSize(short propVal)
{
	SetProperty(0x22, VT_I2, propVal);
}

long CPrintInfo1::GetSettingsPaperWidth() const
{
	long result;
	GetProperty(0x23, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetSettingsPaperWidth(long propVal)
{
	SetProperty(0x23, VT_I4, propVal);
}

long CPrintInfo1::GetSettingsPaperHeight() const
{
	long result;
	GetProperty(0x24, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetSettingsPaperHeight(long propVal)
{
	SetProperty(0x24, VT_I4, propVal);
}

short CPrintInfo1::GetSettingsPaperBin() const
{
	short result;
	GetProperty(0x25, VT_I2, (void*)&result);
	return result;
}

void CPrintInfo1::SetSettingsPaperBin(short propVal)
{
	SetProperty(0x25, VT_I2, propVal);
}

long CPrintInfo1::GetUnitsPerInch() const
{
	long result;
	GetProperty(0x18, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetUnitsPerInch(long propVal)
{
	SetProperty(0x18, VT_I4, propVal);
}

BOOL CPrintInfo1::GetPreviewAllowFileOps() const
{
	BOOL result;
	GetProperty(0x2d, VT_BOOL, (void*)&result);
	return result;
}

void CPrintInfo1::SetPreviewAllowFileOps(BOOL propVal)
{
	SetProperty(0x2d, VT_BOOL, propVal);
}

long CPrintInfo1::GetPreviewInitZoom() const
{
	long result;
	GetProperty(0x2e, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetPreviewInitZoom(long propVal)
{
	SetProperty(0x2e, VT_I4, propVal);
}

long CPrintInfo1::GetPreviewInitPosX() const
{
	long result;
	GetProperty(0x2f, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetPreviewInitPosX(long propVal)
{
	SetProperty(0x2f, VT_I4, propVal);
}

long CPrintInfo1::GetPreviewInitPosY() const
{
	long result;
	GetProperty(0x30, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetPreviewInitPosY(long propVal)
{
	SetProperty(0x30, VT_I4, propVal);
}

long CPrintInfo1::GetPreviewInitWidth() const
{
	long result;
	GetProperty(0x31, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetPreviewInitWidth(long propVal)
{
	SetProperty(0x31, VT_I4, propVal);
}

long CPrintInfo1::GetPreviewInitHeight() const
{
	long result;
	GetProperty(0x32, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetPreviewInitHeight(long propVal)
{
	SetProperty(0x32, VT_I4, propVal);
}

long CPrintInfo1::GetPreviewInitScreenFill() const
{
	long result;
	GetProperty(0x33, VT_I4, (void*)&result);
	return result;
}

void CPrintInfo1::SetPreviewInitScreenFill(long propVal)
{
	SetProperty(0x33, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CPrintInfo1 operations

void CPrintInfo1::PrintData(const VARIANT& selector)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&selector);
}

void CPrintInfo1::PrintPreview(const VARIANT& selector)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&selector);
}

void CPrintInfo1::PageSetup()
{
	InvokeHelper(0x14, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CPrintInfo1::SetMenuText(long Index, LPCTSTR Text)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Index, Text);
}

CString CPrintInfo1::GetMenuText(long Index)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Index);
	return result;
}

void CPrintInfo1::SubstituteFont(LPCTSTR UnavailableFont, const VARIANT& AvailableFont)
{
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		UnavailableFont, &AvailableFont);
}

CString CPrintInfo1::GetSubstituteFont(LPCTSTR UnavailableFont)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		UnavailableFont);
	return result;
}
