



#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CProperty;

/////////////////////////////////////////////////////////////////////////////
// CProperties wrapper class

class CProperties : public COleDispatchDriver
{
public:
	CProperties() {}		// Calls COleDispatchDriver default constructor
	CProperties(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CProperties(const CProperties& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	void Refresh();
	CProperty GetItem(const VARIANT& Index);
};





