//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Information.rc
//
#define IDS_KEYNAME                     18
#define IDS_GRID_AATDATABASE            19
#define IDS_GRID_QUERY                  20
#define IDS_PANE_POU                    21
#define IDS_PANE_QUERY                  22
#define IDS_GRID_POUDATABASE            23
#define IDS_MANAGER_ATLASPOU            24
#define IDS_MANAGER_MAPPOU              25
#define IDS_KEYMAP                      26
#define IDS_KEYLAYER                    27
#define IDS_STRING_ALL                  28
#define IDS_PANE_TABLE                  29
#define IDD_SQL                         30
#define IDD_STAT                        31
#define IDB_ITEMSTATE                   32
#define IDR_PANE_POU                    33
#define IDR_POU1                        34
#define IDR_POU2                        35
#define IDI_QUERY                       36
#define IDI_POU                         37
#define IDI_TABLE                       38
#define IDR_SORT                        40
#define IDB_PANE_POU                    41
#define IDD_INFO                        42
#define IDB_PANE_ATLAS24                43
#define IDD_MDINFO                      44
#define IDD_FIELDPICKER                 46
#define IDR_ATTRIBUTE_HTML              48
#define IDD_WHEREPICK                   49
#define IDR_POI2                        50
#define IDR_DBGRID                      51
#define IDB_SORTIMAGE                   52
#define IDD_DATABASE                    53
#define IDD_ORDERKEY                    54
#define IDD_KEYQUERY                    55
#define IDD_SELECT                      56
#define IDD_COOQUERY                    57
#define IDD_DEGREE                      58
#define IDD_SEXAGE                      59
#define IDD_SQLQUERY                    60
#define IDD_TABLETQUERY                 61
#define IDD_FIELD                       62
#define IDD_WHERE                       63
#define IDD_GEOMQUERY                   64
#define IDD_WHERETEXT                   65
#define IDD_DATABASE1                   66
#define IDB_SORT24                      67
#define IDB_DBGRID_TOOLBAR              100
#define IDD_COLUMNPICKER                104
#define IDD_GEOMQUERY1                  105
#define IDC_KEY                         528
#define IDC_QUERY                       529
#define IDC_TYPECOMBO                   530
#define IDC_MINIMUMSCALE                531
#define IDC_ODBCDSN                     532
#define IDC_DATABASE                    533
#define IDC_SERVER                      534
#define IDC_ODBCUID                     535
#define IDC_ODBCPWD                     536
#define IDC_SETUP                       537
#define IDC_LISTCTRL                    538
#define IDC_TABLECOMBO                  539
#define IDC_COUNT                       540
#define IDC_LOCATE                      541
#define IDC_CLASSCOMBO1                 542
#define IDC_MAPCOMBO                    543
#define IDC_CLASSCOMBO2                 544
#define IDC_GETSQL                      545
#define IDC_LIST                        546
#define IDC_TYPE                        547
#define IDC_SQL                         548
#define IDC_MDINFOCTRL                  549
#define IDC_MAX                         550
#define IDC_MIN                         551
#define IDC_AVG                         552
#define IDC_SUM                         553
#define IDC_FIELD                       554
#define IDC_STREET                      555
#define IDC_TABLET                      556
#define IDC_TABLETRDC                   557
#define IDC_TABLETGRID                  558
#define IDC_FIELDCOMBO                  559
#define IDC_ADD                         560
#define IDC_CLEAR                       561
#define IDC_SIZE                        562
#define IDC_DEFAULT                     564
#define IDC_NEW                         565
#define IDC_STATIC1                     566
#define IDC_POICODE1                    567
#define IDC_FIRSTKEY                    568
#define IDC_POICODE2                    569
#define IDC_SECONDKEK                   570
#define IDC_POICODE3                    571
#define IDC_FASC                        572
#define IDC_STATIC2                     573
#define IDC_FDESC                       574
#define IDC_STATIC3                     575
#define IDC_SASC                        576
#define IDC_ADMCODE                     577
#define IDC_SDESC                       578
#define IDC_ROADCODE                    579
#define IDC_WHEREFRAME                  580
#define IDC_WHEREEDIT                   581
#define IDC_STATMENT                    582
#define IDC_COMBO1                      583
#define IDC_COMBO2                      584
#define IDC_COMBODBMS                   585
#define IDC_CHECK1                      586
#define IDC_COMBO3                      587
#define IDC_BUTTON1                     588
#define IDC_TABLE                       589
#define IDC_DELETE                      590
#define IDC_COLUMNS                     591
#define IDC_FIELDLIST                   592
#define IDC_MOVEUP                      593
#define IDC_MOVEDOWN                    594
#define IDC_MAXIMUMSCALE                595
#define IDC_LONGITUDE                   596
#define IDC_LATITUDE                    597
#define IDC_LONM                        598
#define IDC_GPS                         599
#define IDC_LATM                        600
#define IDC_LONS                        601
#define IDC_LATS                        602
#define IDC_LOND                        603
#define IDC_LATD                        604
#define IDC_WGS84                       605
#define IDC_Y                           1000
#define IDC_X                           1001
#define IDC_TDBGRID1                    1004
#define ID_NEW_FOLDER                   35000
#define ID_MENUBUTTON                   35001
#define ID_SORT_MENU                    35002
#define ID_POU_DELETE                   35003
#define ID_POU_NEW                      35004
#define ID_POU_SETWHERE                 35005
#define ID_POU_SETHINT                  35006
#define ID_POU_SETTAG                   35007
#define ID_POU_ALLON                    35008
#define ID_POU_ALLOFF                   35009
#define ID_GRID_INSERT                  35010
#define ID_GRID_DELETE                  35011
#define ID_GRID_FITTOHEADER             35012
#define ID_GRID_FITTOWINDOW             35013
#define ID_GRID_ORDER                   35014
#define ID_GRID_ORDERASCE               35015
#define ID_GRID_ORDERDESC               35016
#define ID_GRID_QUERY                   35017
#define ID_GRID_STAT                    35018
#define ID_GRID_GEOMALL                 35019
#define ID_GRID_GEOM                    35020
#define ID_GRID_GEOMRADIO               35021
#define ID_GRID_LOCATE                  35022
#define ID_GRID_EMBED                   35023
#define ID_GRID_NEXT                    35024
#define ID_GRID_EXPORT                  35025
#define ID_POU_SETSPOT                  35026
#define ID_POU_DATASOURCE               35028
#define ID_POU_CONNECTION               35030
#define ID_GRID_REFRESH                 35031
#define ID_GRID_PAGEMODE                35032
#define ID_GRID_PAGEFIRST               35033
#define ID_GRID_PAGEPREV                35034
#define ID_GRID_PAGELIST                35035
#define ID_GRID_PAGENEXT                35036
#define ID_GRID_PAGELAST                35037

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         35038
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           1100
#endif
#endif
