// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "stdafx.h"
#include "selbookmarks.h"

/////////////////////////////////////////////////////////////////////////////
// CSelBookmarks properties

long CSelBookmarks::GetCount() const
{
	long result;
	GetProperty(0x7d2, VT_I4, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CSelBookmarks operations

LPUNKNOWN CSelBookmarks::Get_NewEnum()
{
	LPUNKNOWN result;
	InvokeHelper(0xfffffffc, DISPATCH_PROPERTYGET, VT_UNKNOWN, (void*)&result, nullptr);
	return result;
}

VARIANT CSelBookmarks::GetItem(const VARIANT& Index)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, parms,
		&Index);
	return result;
}

void CSelBookmarks::Add(const VARIANT& Bookmark)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x7d5, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Bookmark);
}

void CSelBookmarks::Remove(const VARIANT& Index)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x7d6, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Index);
}

void CSelBookmarks::Clear()
{
	InvokeHelper(0xfffffdd6, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}
