#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

// Dispatch interfaces referenced by this interface
class CSplit;

/////////////////////////////////////////////////////////////////////////////
// CSplits wrapper class

class CSplits : public COleDispatchDriver
{
	public:
	CSplits()
	{
	} // Calls COleDispatchDriver default constructor
	CSplits(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	CSplits(const CSplits& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
	public:
	long GetCount() const;

	// Operations
	public:
	LPUNKNOWN Get_NewEnum();
	CSplit GetItem(const VARIANT& Index);
	CSplit Add(short Index);
	void Remove(const VARIANT& Index);
};
