// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "stdafx.h"
#include "split.h"

// Dispatch interfaces referenced by this interface
#include "font.h"
#include "styledisp.h"
#include "columns.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CSplit properties

unsigned long CSplit::GetBackColor() const
{
	unsigned long result;
	GetProperty(0x15, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetBackColor(unsigned long propVal)
{
	SetProperty(0x15, VT_I4, propVal);
}

unsigned long CSplit::GetForeColor() const
{
	unsigned long result;
	GetProperty(0x16, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetForeColor(unsigned long propVal)
{
	SetProperty(0x16, VT_I4, propVal);
}

unsigned long CSplit::GetHeadBackColor() const
{
	unsigned long result;
	GetProperty(0x17, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetHeadBackColor(unsigned long propVal)
{
	SetProperty(0x17, VT_I4, propVal);
}

unsigned long CSplit::GetHeadForeColor() const
{
	unsigned long result;
	GetProperty(0x18, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetHeadForeColor(unsigned long propVal)
{
	SetProperty(0x18, VT_I4, propVal);
}

unsigned long CSplit::GetFooterBackColor() const
{
	unsigned long result;
	GetProperty(0x38, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetFooterBackColor(unsigned long propVal)
{
	SetProperty(0x38, VT_I4, propVal);
}

unsigned long CSplit::GetFooterForeColor() const
{
	unsigned long result;
	GetProperty(0x39, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetFooterForeColor(unsigned long propVal)
{
	SetProperty(0x39, VT_I4, propVal);
}

unsigned long CSplit::GetEditBackColor() const
{
	unsigned long result;
	GetProperty(0x19, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetEditBackColor(unsigned long propVal)
{
	SetProperty(0x19, VT_I4, propVal);
}

unsigned long CSplit::GetEditForeColor() const
{
	unsigned long result;
	GetProperty(0x1a, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetEditForeColor(unsigned long propVal)
{
	SetProperty(0x1a, VT_I4, propVal);
}

BOOL CSplit::GetExtendRightColumn() const
{
	BOOL result;
	GetProperty(0x20, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetExtendRightColumn(BOOL propVal)
{
	SetProperty(0x20, VT_BOOL, propVal);
}

BOOL CSplit::GetPartialRightColumn() const
{
	BOOL result;
	GetProperty(0x3a, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetPartialRightColumn(BOOL propVal)
{
	SetProperty(0x3a, VT_BOOL, propVal);
}

BOOL CSplit::GetAnchorRightColumn() const
{
	BOOL result;
	GetProperty(0x3b, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetAnchorRightColumn(BOOL propVal)
{
	SetProperty(0x3b, VT_BOOL, propVal);
}

unsigned long CSplit::GetInactiveBackColor() const
{
	unsigned long result;
	GetProperty(0x1b, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetInactiveBackColor(unsigned long propVal)
{
	SetProperty(0x1b, VT_I4, propVal);
}

unsigned long CSplit::GetInactiveForeColor() const
{
	unsigned long result;
	GetProperty(0x1c, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetInactiveForeColor(unsigned long propVal)
{
	SetProperty(0x1c, VT_I4, propVal);
}

unsigned long CSplit::GetSelectedBackColor() const
{
	unsigned long result;
	GetProperty(0x1d, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetSelectedBackColor(unsigned long propVal)
{
	SetProperty(0x1d, VT_I4, propVal);
}

unsigned long CSplit::GetSelectedForeColor() const
{
	unsigned long result;
	GetProperty(0x1e, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetSelectedForeColor(unsigned long propVal)
{
	SetProperty(0x1e, VT_I4, propVal);
}

COleFont CSplit::GetFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(0xb, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CSplit::SetFont(LPDISPATCH propVal)
{
	SetProperty(0xb, VT_DISPATCH, propVal);
}

COleFont CSplit::GetHeadFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x14, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CSplit::SetHeadFont(LPDISPATCH propVal)
{
	SetProperty(0x14, VT_DISPATCH, propVal);
}

COleFont CSplit::GetFooterFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x37, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CSplit::SetFooterFont(LPDISPATCH propVal)
{
	SetProperty(0x37, VT_DISPATCH, propVal);
}

BOOL CSplit::GetLocked() const
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetLocked(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

short CSplit::GetIndex() const
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

short CSplit::GetScrollGroup() const
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CSplit::SetScrollGroup(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

long CSplit::GetMarqueeStyle() const
{
	long result;
	GetProperty(0x1f, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetMarqueeStyle(long propVal)
{
	SetProperty(0x1f, VT_I4, propVal);
}

BOOL CSplit::GetAllowSizing() const
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetAllowSizing(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

BOOL CSplit::GetAllowFocus() const
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetAllowFocus(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

long CSplit::GetSizeMode() const
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetSizeMode(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

VARIANT CSplit::GetSize() const
{
	VARIANT result;
	GetProperty(0x6, VT_VARIANT, (void*)&result);
	return result;
}

void CSplit::SetSize(const VARIANT& propVal)
{
	SetProperty(0x6, VT_VARIANT, &propVal);
}

BOOL CSplit::GetAllowRowSizing() const
{
	BOOL result;
	GetProperty(0xf, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetAllowRowSizing(BOOL propVal)
{
	SetProperty(0xf, VT_BOOL, propVal);
}

BOOL CSplit::GetRecordSelectors() const
{
	BOOL result;
	GetProperty(0x10, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetRecordSelectors(BOOL propVal)
{
	SetProperty(0x10, VT_BOOL, propVal);
}

float CSplit::GetRecordSelectorWidth() const
{
	float result;
	GetProperty(0x47, VT_R4, (void*)&result);
	return result;
}

void CSplit::SetRecordSelectorWidth(float propVal)
{
	SetProperty(0x47, VT_R4, propVal);
}

long CSplit::GetScrollBars() const
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetScrollBars(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

CStyleDisp CSplit::GetStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0xc, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetStyle(LPDISPATCH propVal)
{
	SetProperty(0xc, VT_DISPATCH, propVal);
}

BOOL CSplit::GetCurrentCellVisible() const
{
	BOOL result;
	GetProperty(0x21, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetCurrentCellVisible(BOOL propVal)
{
	SetProperty(0x21, VT_BOOL, propVal);
}

VARIANT CSplit::GetFirstRow() const
{
	VARIANT result;
	GetProperty(0x22, VT_VARIANT, (void*)&result);
	return result;
}

void CSplit::SetFirstRow(const VARIANT& propVal)
{
	SetProperty(0x22, VT_VARIANT, &propVal);
}

short CSplit::GetLeftCol() const
{
	short result;
	GetProperty(0x23, VT_I2, (void*)&result);
	return result;
}

void CSplit::SetLeftCol(short propVal)
{
	SetProperty(0x23, VT_I2, propVal);
}

CStyleDisp CSplit::GetHeadingStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0xd, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetHeadingStyle(LPDISPATCH propVal)
{
	SetProperty(0xd, VT_DISPATCH, propVal);
}

CStyleDisp CSplit::GetFooterStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x36, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetFooterStyle(LPDISPATCH propVal)
{
	SetProperty(0x36, VT_DISPATCH, propVal);
}

CStyleDisp CSplit::GetEditorStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0xe, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetEditorStyle(LPDISPATCH propVal)
{
	SetProperty(0xe, VT_DISPATCH, propVal);
}

CStyleDisp CSplit::GetInactiveStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x12, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetInactiveStyle(LPDISPATCH propVal)
{
	SetProperty(0x12, VT_DISPATCH, propVal);
}

CStyleDisp CSplit::GetSelectedStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x13, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetSelectedStyle(LPDISPATCH propVal)
{
	SetProperty(0x13, VT_DISPATCH, propVal);
}

CStyleDisp CSplit::GetHighlightRowStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x2e, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetHighlightRowStyle(LPDISPATCH propVal)
{
	SetProperty(0x2e, VT_DISPATCH, propVal);
}

CStyleDisp CSplit::GetEvenRowStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x30, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetEvenRowStyle(LPDISPATCH propVal)
{
	SetProperty(0x30, VT_DISPATCH, propVal);
}

CStyleDisp CSplit::GetOddRowStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x31, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetOddRowStyle(LPDISPATCH propVal)
{
	SetProperty(0x31, VT_DISPATCH, propVal);
}

CStyleDisp CSplit::GetCaptionStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x34, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetCaptionStyle(LPDISPATCH propVal)
{
	SetProperty(0x34, VT_DISPATCH, propVal);
}

short CSplit::GetSelStartCol() const
{
	short result;
	GetProperty(0x24, VT_I2, (void*)&result);
	return result;
}

void CSplit::SetSelStartCol(short propVal)
{
	SetProperty(0x24, VT_I2, propVal);
}

short CSplit::GetSelEndCol() const
{
	short result;
	GetProperty(0x25, VT_I2, (void*)&result);
	return result;
}

void CSplit::SetSelEndCol(short propVal)
{
	SetProperty(0x25, VT_I2, propVal);
}

BOOL CSplit::GetAllowColSelect() const
{
	BOOL result;
	GetProperty(0x29, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetAllowColSelect(BOOL propVal)
{
	SetProperty(0x29, VT_BOOL, propVal);
}

BOOL CSplit::GetAllowColMove() const
{
	BOOL result;
	GetProperty(0x2a, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetAllowColMove(BOOL propVal)
{
	SetProperty(0x2a, VT_BOOL, propVal);
}

BOOL CSplit::GetAllowRowSelect() const
{
	BOOL result;
	GetProperty(0x2b, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetAllowRowSelect(BOOL propVal)
{
	SetProperty(0x2b, VT_BOOL, propVal);
}

float CSplit::GetVScrollWidth() const
{
	float result;
	GetProperty(0x2c, VT_R4, (void*)&result);
	return result;
}

void CSplit::SetVScrollWidth(float propVal)
{
	SetProperty(0x2c, VT_R4, propVal);
}

float CSplit::GetHScrollHeight() const
{
	float result;
	GetProperty(0x2d, VT_R4, (void*)&result);
	return result;
}

void CSplit::SetHScrollHeight(float propVal)
{
	SetProperty(0x2d, VT_R4, propVal);
}

BOOL CSplit::GetFetchRowStyle() const
{
	BOOL result;
	GetProperty(0x2f, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetFetchRowStyle(BOOL propVal)
{
	SetProperty(0x2f, VT_BOOL, propVal);
}

BOOL CSplit::GetAlternatingRowStyle() const
{
	BOOL result;
	GetProperty(0x32, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetAlternatingRowStyle(BOOL propVal)
{
	SetProperty(0x32, VT_BOOL, propVal);
}

CString CSplit::GetCaption() const
{
	CString result;
	GetProperty(0x33, VT_BSTR, (void*)&result);
	return result;
}

void CSplit::SetCaption(LPCTSTR propVal)
{
	SetProperty(0x33, VT_BSTR, propVal);
}

long CSplit::GetDividerStyle() const
{
	long result;
	GetProperty(0x35, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetDividerStyle(long propVal)
{
	SetProperty(0x35, VT_I4, propVal);
}

unsigned long CSplit::GetDividerColor() const
{
	unsigned long result;
	GetProperty(0x40, VT_I4, (void*)&result);
	return result;
}

void CSplit::SetDividerColor(unsigned long propVal)
{
	SetProperty(0x40, VT_I4, propVal);
}

BOOL CSplit::GetFilterBar() const
{
	BOOL result;
	GetProperty(0x42, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetFilterBar(BOOL propVal)
{
	SetProperty(0x42, VT_BOOL, propVal);
}

short CSplit::GetFilterActive() const
{
	short result;
	GetProperty(0x43, VT_I2, (void*)&result);
	return result;
}

void CSplit::SetFilterActive(short propVal)
{
	SetProperty(0x43, VT_I2, propVal);
}

CStyleDisp CSplit::GetRecordSelectorStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x41, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetRecordSelectorStyle(LPDISPATCH propVal)
{
	SetProperty(0x41, VT_DISPATCH, propVal);
}

CStyleDisp CSplit::GetFilterBarStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x44, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CSplit::SetFilterBarStyle(LPDISPATCH propVal)
{
	SetProperty(0x44, VT_DISPATCH, propVal);
}

BOOL CSplit::GetSelRange() const
{
	BOOL result;
	GetProperty(0x45, VT_BOOL, (void*)&result);
	return result;
}

BOOL CSplit::GetSpringMode() const
{
	BOOL result;
	GetProperty(0x46, VT_BOOL, (void*)&result);
	return result;
}

void CSplit::SetSpringMode(BOOL propVal)
{
	SetProperty(0x46, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSplit operations

CColumns CSplit::GetColumns()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xa, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CColumns(pDispatch);
}

void CSplit::AddCellStyle(short Condition, const VARIANT& Style)
{
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition, &Style);
}

void CSplit::AddRegexCellStyle(short Condition, const VARIANT& Style, LPCTSTR Regex)
{
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition, &Style, Regex);
}

void CSplit::ClearCellStyle(short Condition)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition);
}

void CSplit::ClearRegexCellStyle(short Condition, const VARIANT& Regex)
{
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition, &Regex);
}

void CSplit::ClearSelCols()
{
	InvokeHelper(0x26, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}
