#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

// Dispatch interfaces referenced by this interface
class COleFont;
class CStyleDisp;
class CColumns;

/////////////////////////////////////////////////////////////////////////////
// CSplit wrapper class

class CSplit : public COleDispatchDriver
{
	public:
	CSplit()
	{
	} // Calls COleDispatchDriver default constructor
	CSplit(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	CSplit(const CSplit& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
	public:
	unsigned long GetBackColor() const;
	void SetBackColor(unsigned long);
	unsigned long GetForeColor() const;
	void SetForeColor(unsigned long);
	unsigned long GetHeadBackColor() const;
	void SetHeadBackColor(unsigned long);
	unsigned long GetHeadForeColor() const;
	void SetHeadForeColor(unsigned long);
	unsigned long GetFooterBackColor() const;
	void SetFooterBackColor(unsigned long);
	unsigned long GetFooterForeColor() const;
	void SetFooterForeColor(unsigned long);
	unsigned long GetEditBackColor() const;
	void SetEditBackColor(unsigned long);
	unsigned long GetEditForeColor() const;
	void SetEditForeColor(unsigned long);
	BOOL GetExtendRightColumn() const;
	void SetExtendRightColumn(BOOL);
	BOOL GetShowCollapseExpandIcons();
	void SetShowCollapseExpandIcons(BOOL);
	BOOL GetPartialRightColumn() const;
	void SetPartialRightColumn(BOOL);
	BOOL GetAnchorRightColumn() const;
	void SetAnchorRightColumn(BOOL);
	unsigned long GetInactiveBackColor() const;
	void SetInactiveBackColor(unsigned long);
	unsigned long GetInactiveForeColor() const;
	void SetInactiveForeColor(unsigned long);
	unsigned long GetSelectedBackColor() const;
	void SetSelectedBackColor(unsigned long);
	unsigned long GetSelectedForeColor() const;
	void SetSelectedForeColor(unsigned long);
	COleFont GetFont() const;
	void SetFont(LPDISPATCH);
	COleFont GetHeadFont() const;
	void SetHeadFont(LPDISPATCH);
	COleFont GetFooterFont() const;
	void SetFooterFont(LPDISPATCH);
	BOOL GetLocked() const;
	void SetLocked(BOOL);
	short GetIndex() const;
	short GetScrollGroup() const;
	void SetScrollGroup(short);
	long GetMarqueeStyle() const;
	void SetMarqueeStyle(long);
	BOOL GetAllowSizing() const;
	void SetAllowSizing(BOOL);
	BOOL GetAllowFocus() const;
	void SetAllowFocus(BOOL);
	long GetSizeMode() const;
	void SetSizeMode(long);
	VARIANT GetSize() const;
	void SetSize(const VARIANT&);
	BOOL GetAllowRowSizing() const;
	void SetAllowRowSizing(BOOL);
	BOOL GetRecordSelectors() const;
	void SetRecordSelectors(BOOL);
	float GetRecordSelectorWidth() const;
	void SetRecordSelectorWidth(float);
	long GetScrollBars() const;
	void SetScrollBars(long);
	CStyleDisp GetStyle() const;
	void SetStyle(LPDISPATCH);
	BOOL GetCurrentCellVisible() const;
	void SetCurrentCellVisible(BOOL);
	VARIANT GetFirstRow() const;
	void SetFirstRow(const VARIANT&);
	short GetLeftCol() const;
	void SetLeftCol(short);
	CStyleDisp GetHeadingStyle() const;
	void SetHeadingStyle(LPDISPATCH);
	CStyleDisp GetFooterStyle() const;
	void SetFooterStyle(LPDISPATCH);
	CStyleDisp GetEditorStyle() const;
	void SetEditorStyle(LPDISPATCH);
	CStyleDisp GetInactiveStyle() const;
	void SetInactiveStyle(LPDISPATCH);
	CStyleDisp GetSelectedStyle() const;
	void SetSelectedStyle(LPDISPATCH);
	CStyleDisp GetHighlightRowStyle() const;
	void SetHighlightRowStyle(LPDISPATCH);
	CStyleDisp GetEvenRowStyle() const;
	void SetEvenRowStyle(LPDISPATCH);
	CStyleDisp GetOddRowStyle() const;
	void SetOddRowStyle(LPDISPATCH);
	CStyleDisp GetCaptionStyle() const;
	void SetCaptionStyle(LPDISPATCH);
	short GetSelStartCol() const;
	void SetSelStartCol(short);
	short GetSelEndCol() const;
	void SetSelEndCol(short);
	BOOL GetAllowColSelect() const;
	void SetAllowColSelect(BOOL);
	BOOL GetAllowColMove() const;
	void SetAllowColMove(BOOL);
	BOOL GetAllowRowSelect() const;
	void SetAllowRowSelect(BOOL);
	float GetVScrollWidth() const;
	void SetVScrollWidth(float);
	float GetHScrollHeight() const;
	void SetHScrollHeight(float);
	BOOL GetFetchRowStyle() const;
	void SetFetchRowStyle(BOOL);
	BOOL GetAlternatingRowStyle() const;
	void SetAlternatingRowStyle(BOOL);
	CString GetCaption() const;
	void SetCaption(LPCTSTR);
	long GetDividerStyle() const;
	void SetDividerStyle(long);
	unsigned long GetDividerColor() const;
	void SetDividerColor(unsigned long);
	BOOL GetFilterBar() const;
	void SetFilterBar(BOOL);
	short GetFilterActive() const;
	void SetFilterActive(short);
	CStyleDisp GetRecordSelectorStyle() const;
	void SetRecordSelectorStyle(LPDISPATCH);
	CStyleDisp GetFilterBarStyle() const;
	void SetFilterBarStyle(LPDISPATCH);
	BOOL GetSelRange() const;
	BOOL GetSpringMode() const;
	void SetSpringMode(BOOL);

	// Operations
	public:
	CColumns GetColumns();
	void AddCellStyle(short Condition, const VARIANT& Style);
	void AddRegexCellStyle(short Condition, const VARIANT& Style, LPCTSTR Regex);
	void ClearCellStyle(short Condition);
	void ClearRegexCellStyle(short Condition, const VARIANT& Regex);
	void ClearSelCols();
};
