#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

// Dispatch interfaces referenced by this interface
class CStyleDisp;

/////////////////////////////////////////////////////////////////////////////
// CStyles wrapper class

class CStyles : public COleDispatchDriver
{
	public:
	CStyles()
	{
	} // Calls COleDispatchDriver default constructor
	CStyles(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	CStyles(const CStyles& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
	public:
	long GetCount() const;

	// Operations
	public:
	LPUNKNOWN Get_NewEnum();
	CStyleDisp GetItem(const VARIANT& Index);
	CStyleDisp Add(LPCTSTR Name);
	void Remove(const VARIANT& Index);
};
