// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "stdafx.h"
#include "styledisp.h"

// Dispatch interfaces referenced by this interface
#include "Font.h"

/////////////////////////////////////////////////////////////////////////////
// CStyleDisp properties

unsigned long CStyleDisp::GetForeColor() const
{
	unsigned long result;
	GetProperty(0xb, VT_I4, (void*)&result);
	return result;
}

void CStyleDisp::SetForeColor(unsigned long propVal)
{
	SetProperty(0xb, VT_I4, propVal);
}

unsigned long CStyleDisp::GetBackColor() const
{
	unsigned long result;
	GetProperty(0xc, VT_I4, (void*)&result);
	return result;
}

void CStyleDisp::SetBackColor(unsigned long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

COleFont CStyleDisp::GetFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x1, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CStyleDisp::SetFont(LPDISPATCH propVal)
{
	SetProperty(0x1, VT_DISPATCH, propVal);
}

long CStyleDisp::GetAlignment() const
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CStyleDisp::SetAlignment(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CStyleDisp::GetVerticalAlignment() const
{
	long result;
	GetProperty(0x9, VT_I4, (void*)&result);
	return result;
}

void CStyleDisp::SetVerticalAlignment(long propVal)
{
	SetProperty(0x9, VT_I4, propVal);
}

BOOL CStyleDisp::GetLocked() const
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CStyleDisp::SetLocked(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

CString CStyleDisp::GetName() const
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

VARIANT CStyleDisp::GetParent() const
{
	VARIANT result;
	GetProperty(0x8, VT_VARIANT, (void*)&result);
	return result;
}

void CStyleDisp::SetParent(const VARIANT& propVal)
{
	SetProperty(0x8, VT_VARIANT, &propVal);
}

VARIANT CStyleDisp::GetValue() const
{
	VARIANT result;
	GetProperty(0x0, VT_VARIANT, (void*)&result);
	return result;
}

void CStyleDisp::SetValue(const VARIANT& propVal)
{
	SetProperty(0x0, VT_VARIANT, &propVal);
}

BOOL CStyleDisp::GetWrapText() const
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CStyleDisp::SetWrapText(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

BOOL CStyleDisp::GetTransparentForegroundPicture() const
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}

void CStyleDisp::SetTransparentForegroundPicture(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}

VARIANT CStyleDisp::GetForegroundPicture() const
{
	VARIANT result;
	GetProperty(0xf, VT_VARIANT, (void*)&result);
	return result;
}

void CStyleDisp::SetForegroundPicture(const VARIANT& propVal)
{
	SetProperty(0xf, VT_VARIANT, &propVal);
}

VARIANT CStyleDisp::GetBackgroundPicture() const
{
	VARIANT result;
	GetProperty(0x10, VT_VARIANT, (void*)&result);
	return result;
}

void CStyleDisp::SetBackgroundPicture(const VARIANT& propVal)
{
	SetProperty(0x10, VT_VARIANT, &propVal);
}

long CStyleDisp::GetForegroundPicturePosition() const
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CStyleDisp::SetForegroundPicturePosition(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

long CStyleDisp::GetBackgroundPictureDrawMode() const
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CStyleDisp::SetBackgroundPictureDrawMode(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

long CStyleDisp::GetBorderAppearance() const
{
	long result;
	GetProperty(0x13, VT_I4, (void*)&result);
	return result;
}

void CStyleDisp::SetBorderAppearance(long propVal)
{
	SetProperty(0x13, VT_I4, propVal);
}

short CStyleDisp::GetBorderSize() const
{
	short result;
	GetProperty(0x14, VT_I2, (void*)&result);
	return result;
}

void CStyleDisp::SetBorderSize(short propVal)
{
	SetProperty(0x14, VT_I2, propVal);
}

BOOL CStyleDisp::GetEllipsisText() const
{
	BOOL result;
	GetProperty(0x15, VT_BOOL, (void*)&result);
	return result;
}

void CStyleDisp::SetEllipsisText(BOOL propVal)
{
	SetProperty(0x15, VT_BOOL, propVal);
}

unsigned long CStyleDisp::GetBorderColor() const
{
	unsigned long result;
	GetProperty(0x16, VT_I4, (void*)&result);
	return result;
}

void CStyleDisp::SetBorderColor(unsigned long propVal)
{
	SetProperty(0x16, VT_I4, propVal);
}

short CStyleDisp::GetBorderType() const
{
	short result;
	GetProperty(0x17, VT_I2, (void*)&result);
	return result;
}

void CStyleDisp::SetBorderType(short propVal)
{
	SetProperty(0x17, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CStyleDisp operations

void CStyleDisp::Reset()
{
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}
