#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

// Dispatch interfaces referenced by this interface
class COleFont;
class CStyleDisp;
class CColumns;
class CSplits;
class CStyles;
class CSelBookmarks;
class CPicture;
class CLayouts;
class CPrintInfos;
class CPrintInfo1;
class CErrors;
class CGroupColumns;

/////////////////////////////////////////////////////////////////////////////
// CTrueDBGridCtrl wrapper class

class CTrueDBGridCtrl : public CWnd
{
	protected:
	DECLARE_DYNCREATE(CTrueDBGridCtrl)
	public:
	static CLSID const& GetClsid()//version 7.0
	{
		static CLSID const clsid = {0xDEF7CADC, 0x83C0, 0x11D0, {0xA0, 0xF1, 0x00, 0xA0, 0x24, 0x70, 0x35, 0x00}};
		return clsid;
	}

	//CLSID const& GetClsid()//version 8.0
	//{
	//	static CLSID const clsid
	//		= { 0x44bd92db, 0xd8a8, 0x43a8, { 0x89, 0x0, 0xdd, 0x73, 0x31, 0xa, 0x59, 0xeb } };
	//	return clsid;
	//}
	BOOL Create(LPCTSTR lpszClassName,
	                    LPCTSTR lpszWindowName, DWORD dwStyle,
	                    const RECT& rect,
	                    CWnd* pParentWnd, UINT nId,
	                    CCreateContext* pContext = nullptr) override
	{
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nId);
	}

	BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
	            const RECT& rect, CWnd* pParentWnd, UINT nId,
	            CFile* pPersist = nullptr, BOOL bStorage = FALSE,
	            BSTR bstrLicKey = nullptr)
	{
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nId,
		                     pPersist, bStorage, bstrLicKey);
	}

	// Attributes
	public:
	BOOL GetAllowDelete() const;
	void SetAllowDelete(BOOL);
	BOOL GetAllowAddNew() const;
	void SetAllowAddNew(BOOL);
	BOOL GetAllowRowSizing() const;
	void SetAllowRowSizing(BOOL);
	BOOL GetAllowUpdate() const;
	void SetAllowUpdate(BOOL);
	short GetAppearance() const;
	void SetAppearance(short);
	short GetBorderStyle() const;
	void SetBorderStyle(short);
	VARIANT GetBookmark() const;
	void SetBookmark(const VARIANT&);
	short GetBookmarkType() const;
	void SetBookmarkType(short);
	BOOL GetBatchUpdates() const;
	void SetBatchUpdates(BOOL);
	short GetCol() const;
	void SetCol(short);
	BOOL GetColumnHeaders() const;
	void SetColumnHeaders(BOOL);
	BOOL GetColumnFooters() const;
	void SetColumnFooters(BOOL);
	BOOL GetCurrentCellVisible() const;
	void SetCurrentCellVisible(BOOL);
	BOOL GetCurrentCellModified() const;
	void SetCurrentCellModified(BOOL);
	BOOL GetDataChanged() const;
	void SetDataChanged(BOOL);
	long GetDataMode() const;
	void SetDataMode(long);
	LPUNKNOWN GetDataSource() const;
	void SetDataSource(LPUNKNOWN);
	float GetDefColWidth() const;
	void SetDefColWidth(float);
	BOOL GetEditActive() const;
	void SetEditActive(BOOL);
	BOOL GetEditDropDown() const;
	void SetEditDropDown(BOOL);
	BOOL GetEnabled() const;
	void SetEnabled(BOOL);
	BOOL GetExtendRightColumn() const;
	void SetExtendRightColumn(BOOL);
	BOOL GetPartialRightColumn() const;
	void SetPartialRightColumn(BOOL);
	BOOL GetAnchorRightColumn() const;
	void SetAnchorRightColumn(BOOL);
	VARIANT GetFirstRow() const;
	void SetFirstRow(const VARIANT&);
	COleFont GetHeadFont() const;
	void SetHeadFont(LPDISPATCH);
	COleFont GetFooterFont() const;
	void SetFooterFont(LPDISPATCH);
	float GetHeadLines() const;
	void SetHeadLines(float);
	float GetFootLines() const;
	void SetFootLines(float);
	OLE_HANDLE GetHWnd() const;
	long GetHWndEditor() const;
	BOOL GetMarqueeUnique() const;
	void SetMarqueeUnique(BOOL);
	long GetMarqueeStyle() const;
	void SetMarqueeStyle(long);
	BOOL GetRecordSelectors() const;
	void SetRecordSelectors(BOOL);
	float GetRecordSelectorWidth() const;
	void SetRecordSelectorWidth(float);
	short GetRow() const;
	void SetRow(short);
	long GetRowDividerStyle() const;
	void SetRowDividerStyle(long);
	float GetRowHeight() const;
	void SetRowHeight(float);
	long GetScrollBars() const;
	void SetScrollBars(long);
	long GetSelLength() const;
	void SetSelLength(long);
	long GetSelStart() const;
	void SetSelStart(long);
	CString GetSelText() const;
	void SetSelText(LPCTSTR);
	short GetSelStartCol() const;
	void SetSelStartCol(short);
	short GetSelEndCol() const;
	void SetSelEndCol(short);
	short GetSplit() const;
	void SetSplit(short);
	short GetVisibleCols() const;
	short GetVisibleRows() const;
	OLE_COLOR GetBackColor() const;
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor() const;
	void SetForeColor(OLE_COLOR);
	CString GetCaption() const;
	void SetCaption(LPCTSTR);
	COleFont GetFont() const;
	void SetFont(LPDISPATCH);
	short GetLeftCol() const;
	void SetLeftCol(short);
	BOOL GetAllowArrows() const;
	void SetAllowArrows(BOOL);
	long GetExposeCellMode() const;
	void SetExposeCellMode(long);
	BOOL GetTabAcrossSplits() const;
	void SetTabAcrossSplits(BOOL);
	long GetTabAction() const;
	void SetTabAction(long);
	BOOL GetWrapCellPointer() const;
	void SetWrapCellPointer(BOOL);
	BOOL GetWrapRowPointer() const;
	void SetWrapRowPointer(BOOL);
	CStyleDisp GetStyle() const;
	void SetStyle(LPDISPATCH);
	CStyleDisp GetHeadingStyle() const;
	void SetHeadingStyle(LPDISPATCH);
	CStyleDisp GetFooterStyle() const;
	void SetFooterStyle(LPDISPATCH);
	CStyleDisp GetEditorStyle() const;
	void SetEditorStyle(LPDISPATCH);
	CStyleDisp GetInactiveStyle() const;
	void SetInactiveStyle(LPDISPATCH);
	CStyleDisp GetSelectedStyle() const;
	void SetSelectedStyle(LPDISPATCH);
	CStyleDisp GetCaptionStyle() const;
	void SetCaptionStyle(LPDISPATCH);
	CStyleDisp GetHighlightRowStyle() const;
	void SetHighlightRowStyle(LPDISPATCH);
	CStyleDisp GetEvenRowStyle() const;
	void SetEvenRowStyle(LPDISPATCH);
	CStyleDisp GetOddRowStyle() const;
	void SetOddRowStyle(LPDISPATCH);
	unsigned long GetHeadBackColor() const;
	void SetHeadBackColor(unsigned long);
	unsigned long GetHeadForeColor() const;
	void SetHeadForeColor(unsigned long);
	unsigned long GetFooterBackColor() const;
	void SetFooterBackColor(unsigned long);
	unsigned long GetFooterForeColor() const;
	void SetFooterForeColor(unsigned long);
	unsigned long GetEditBackColor() const;
	void SetEditBackColor(unsigned long);
	unsigned long GetEditForeColor() const;
	void SetEditForeColor(unsigned long);
	unsigned long GetInactiveBackColor() const;
	void SetInactiveBackColor(unsigned long);
	unsigned long GetInactiveForeColor() const;
	void SetInactiveForeColor(unsigned long);
	unsigned long GetSelectedBackColor() const;
	void SetSelectedBackColor(unsigned long);
	unsigned long GetSelectedForeColor() const;
	void SetSelectedForeColor(unsigned long);
	long GetApproxCount() const;
	void SetApproxCount(long);
	CString GetErrorText() const;
	long GetAddNewMode() const;
	BOOL GetAllowColSelect() const;
	void SetAllowColSelect(BOOL);
	BOOL GetAllowColMove() const;
	void SetAllowColMove(BOOL);
	BOOL GetAllowRowSelect() const;
	void SetAllowRowSelect(BOOL);
	VARIANT GetPictureCurrentRow() const;
	void SetPictureCurrentRow(const VARIANT&);
	VARIANT GetPictureModifiedRow() const;
	void SetPictureModifiedRow(const VARIANT&);
	VARIANT GetPictureAddnewRow() const;
	void SetPictureAddnewRow(const VARIANT&);
	VARIANT GetPictureStandardRow() const;
	void SetPictureStandardRow(const VARIANT&);
	VARIANT GetPictureHeaderRow() const;
	void SetPictureHeaderRow(const VARIANT&);
	VARIANT GetPictureFooterRow() const;
	void SetPictureFooterRow(const VARIANT&);
	VARIANT GetMouseIcon() const;
	void SetMouseIcon(const VARIANT&);
	long GetMousePointer() const;
	void SetMousePointer(long);
	LPUNKNOWN GetISVServices() const;
	CString GetText() const;
	void SetText(LPCTSTR);
	CString GetLayoutName() const;
	void SetLayoutName(LPCTSTR);
	CString GetLayoutFileName() const;
	void SetLayoutFileName(LPCTSTR);
	CString GetLayoutURL() const;
	void SetLayoutURL(LPCTSTR);
	long GetMultipleLines() const;
	void SetMultipleLines(long);
	LPDISPATCH GetArray() const;
	void SetArray(LPDISPATCH);
	BOOL GetEmptyRows() const;
	void SetEmptyRows(BOOL);
	long GetCellTips() const;
	void SetCellTips(long);
	float GetVScrollWidth() const;
	void SetVScrollWidth(float);
	float GetHScrollHeight() const;
	void SetHScrollHeight(float);
	BOOL GetBof() const;
	BOOL GetEof() const;
	BOOL GetFetchRowStyle() const;
	void SetFetchRowStyle(BOOL);
	BOOL GetAlternatingRowStyle() const;
	void SetAlternatingRowStyle(BOOL);
	float GetCellTipsWidth() const;
	void SetCellTipsWidth(float);
	long GetCellTipsDelay() const;
	void SetCellTipsDelay(long);
	BOOL GetInsertMode() const;
	void SetInsertMode(BOOL);
	BOOL GetTransparentRowPictures() const;
	void SetTransparentRowPictures(BOOL);
	long GetMultiSelect() const;
	void SetMultiSelect(long);
	CString GetDataMember() const;
	void SetDataMember(LPCTSTR);
	long GetOLEDragMode() const;
	void SetOLEDragMode(long);
	long GetOLEDropMode() const;
	void SetOLEDropMode(long);
	BOOL GetExportEOF() const;
	void SetExportEOF(BOOL);
	VARIANT GetExportNextBookmark() const;
	void SetExportNextBookmark(const VARIANT&);
	short GetBands() const;
	long GetDataView() const;
	void SetDataView(long);
	CString GetGroupByCaption() const;
	void SetGroupByCaption(LPCTSTR);
	long GetAnimateWindow() const;
	void SetAnimateWindow(long);
	long GetAnimateWindowDirection() const;
	void SetAnimateWindowDirection(long);
	long GetAnimateWindowTime() const;
	void SetAnimateWindowTime(long);
	long GetAnimateWindowClose() const;
	void SetAnimateWindowClose(long);
	unsigned long GetDeadAreaBackColor() const;
	void SetDeadAreaBackColor(unsigned long);
	BOOL GetScrollTrack() const;
	void SetScrollTrack(BOOL);
	BOOL GetScrollTips() const;
	void SetScrollTips(BOOL);
	unsigned long GetRowDividerColor() const;
	void SetRowDividerColor(unsigned long);
	unsigned long GetRowSubDividerColor() const;
	void SetRowSubDividerColor(unsigned long);
	long GetDirectionAfterEnter() const;
	void SetDirectionAfterEnter(long);
	long GetDirectionAfterTab() const;
	void SetDirectionAfterTab(long);
	BOOL GetRightToLeft() const;
	void SetRightToLeft(BOOL);
	BOOL GetFilterActive() const;
	void SetFilterActive(BOOL);
	BOOL GetFilterBar() const;
	void SetFilterBar(BOOL);
	long GetMaxRows() const;
	void SetMaxRows(long);
	CStyleDisp GetRecordSelectorStyle() const;
	void SetRecordSelectorStyle(LPDISPATCH);
	short GetDestinationSplit() const;
	VARIANT GetDestinationRow() const;
	short GetDestinationCol() const;
	VARIANT GetPictureFilterBar() const;
	void SetPictureFilterBar(const VARIANT&);
	CStyleDisp GetFilterBarStyle() const;
	void SetFilterBarStyle(LPDISPATCH);
	VARIANT GetChildGrid() const;
	void SetChildGrid(const VARIANT&);
	BOOL GetSelRange() const;
	BOOL GetSpringMode() const;
	void SetSpringMode(BOOL);
	float GetViewColumnCaptionWidth() const;
	void SetViewColumnCaptionWidth(float);
	float GetViewColumnWidth() const;
	void SetViewColumnWidth(float);
	unsigned long GetExpandColor() const;
	void SetExpandColor(unsigned long);
	unsigned long GetCollapseColor() const;
	void SetCollapseColor(unsigned long);

	// Operations
	public:
	void AboutBox();
	CColumns GetColumns();
	CSplits GetSplits();
	CStyles GetStyles();
	CSelBookmarks GetSelBookmarks();
	short ColContaining(float X);
	VARIANT GetBookmark(long RowNum);
	void ReBind();
	VARIANT RowBookmark(short RowNum);
	short RowContaining(float Y);
	float RowTop(short RowNum);
	void Scroll(long Cols, long Rows);
	void Refresh();
	CPicture CaptureImage();
	void AddCellStyle(short Condition, const VARIANT& Style);
	void AddRegexCellStyle(short Condition, const VARIANT& Style, LPCTSTR Regex);
	void ClearCellStyle(short Condition);
	void ClearRegexCellStyle(short Condition, const VARIANT& Regex);
	void ClearSelCols();
	void ClearFields();
	void HoldFields();
	short SplitContaining(float X, float Y);
	long PointAt(float X, float Y);
	void PostMsg(short MsgId);
	void Update();
	void MoveRelative(long offset, const VARIANT& Bookmark);
	void MoveFirst();
	void MoveLast();
	void MoveNext();
	void MovePrevious();
	void Delete();
	void Close(const VARIANT& Repaint);
	void ReOpen(const VARIANT& Bookmark);
	void LoadLayout();
	CLayouts GetLayouts();
	BOOL CellContaining(float X, float Y, long* RowAt, short* ColAt);
	void RefreshRow(const VARIANT& Bookmark);
	void RefreshCol(const VARIANT& Col);
	void RefetchRow(const VARIANT& Bookmark);
	void RefetchCol(const VARIANT& Col);
	void OLEDrag();
	short IsSelected(const VARIANT& Bookmark);
	void ExportToFile(LPCTSTR outPath, BOOL append, const VARIANT& selector, const VARIANT& tableWidth);
	void ExportBegin(const VARIANT& Bookmark);
	void ExportRows(LPCTSTR outPath, BOOL append, long Rows, const VARIANT& tableWidth);
	void ExportEnd();
	void ExportToDelimitedFile(LPCTSTR outPath, const VARIANT& selector, const VARIANT& delim, const VARIANT& prefix, const VARIANT& suffix, const VARIANT& headers);
	CPrintInfos GetPrintInfos();
	CPrintInfo1 GetPrintInfo();
	CErrors GetErrors();
	short GetBand(short ColumnIndex);
	BOOL RowExpanded(short Band);
	void CollapseBand(short Band);
	void ExpandBand(short Band);
	CGroupColumns GetGroupColumns();
	void CollapseChild();
	void ExpandChild();
};
