// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "stdafx.h"
#include "truedbgridctrl.h"

// Dispatch interfaces referenced by this interface
#include "Font.h"
#include "StyleDisp.h"
#include "columns.h"
#include "Splits.h"
#include "Styles.h"
#include "SelBookmarks.h"
#include "Picture.h"
#include "Layouts.h"
#include "PrintInfos.h"
#include "PrintInfo.h"
#include "Errors.h"
#include "GroupColumns.h"

/////////////////////////////////////////////////////////////////////////////
// CTrueDBGridCtrl

IMPLEMENT_DYNCREATE(CTrueDBGridCtrl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTrueDBGridCtrl properties

BOOL CTrueDBGridCtrl::GetAllowDelete() const
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAllowDelete(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetAllowAddNew() const
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAllowAddNew(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetAllowRowSizing() const
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAllowRowSizing(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetAllowUpdate() const
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAllowUpdate(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

short CTrueDBGridCtrl::GetAppearance() const
{
	short result;
	GetProperty(DISPID_APPEARANCE, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAppearance(short propVal)
{
	SetProperty(DISPID_APPEARANCE, VT_I4, propVal);
}

short CTrueDBGridCtrl::GetBorderStyle() const
{
	short result;
	GetProperty(DISPID_BORDERSTYLE, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetBorderStyle(short propVal)
{
	SetProperty(DISPID_BORDERSTYLE, VT_I4, propVal);
}

VARIANT CTrueDBGridCtrl::GetBookmark() const
{
	VARIANT result;
	GetProperty(0x5, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetBookmark(const VARIANT& propVal)
{
	SetProperty(0x5, VT_VARIANT, &propVal);
}

short CTrueDBGridCtrl::GetBookmarkType() const
{
	short result;
	GetProperty(0xa6, VT_I2, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetBookmarkType(short propVal)
{
	SetProperty(0xa6, VT_I2, propVal);
}

BOOL CTrueDBGridCtrl::GetBatchUpdates() const
{
	BOOL result;
	GetProperty(0xa7, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetBatchUpdates(BOOL propVal)
{
	SetProperty(0xa7, VT_BOOL, propVal);
}

short CTrueDBGridCtrl::GetCol() const
{
	short result;
	GetProperty(0x6, VT_I2, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetCol(short propVal)
{
	SetProperty(0x6, VT_I2, propVal);
}

BOOL CTrueDBGridCtrl::GetColumnHeaders() const
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetColumnHeaders(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetColumnFooters() const
{
	BOOL result;
	GetProperty(0x8f, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetColumnFooters(BOOL propVal)
{
	SetProperty(0x8f, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetCurrentCellVisible() const
{
	BOOL result;
	GetProperty(0x48, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetCurrentCellVisible(BOOL propVal)
{
	SetProperty(0x48, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetCurrentCellModified() const
{
	BOOL result;
	GetProperty(0x40, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetCurrentCellModified(BOOL propVal)
{
	SetProperty(0x40, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetDataChanged() const
{
	BOOL result;
	GetProperty(0x46, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetDataChanged(BOOL propVal)
{
	SetProperty(0x46, VT_BOOL, propVal);
}

long CTrueDBGridCtrl::GetDataMode() const
{
	long result;
	GetProperty(0x25, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetDataMode(long propVal)
{
	SetProperty(0x25, VT_I4, propVal);
}

LPUNKNOWN CTrueDBGridCtrl::GetDataSource() const
{
	LPUNKNOWN result;
	GetProperty(0x9, VT_UNKNOWN, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetDataSource(LPUNKNOWN propVal)
{
	SetProperty(0x9, VT_UNKNOWN, propVal);
}

float CTrueDBGridCtrl::GetDefColWidth() const
{
	float result;
	GetProperty(0xa, VT_R4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetDefColWidth(float propVal)
{
	SetProperty(0xa, VT_R4, propVal);
}

BOOL CTrueDBGridCtrl::GetEditActive() const
{
	BOOL result;
	GetProperty(0x3f, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetEditActive(BOOL propVal)
{
	SetProperty(0x3f, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetEditDropDown() const
{
	BOOL result;
	GetProperty(0x50, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetEditDropDown(BOOL propVal)
{
	SetProperty(0x50, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetEnabled() const
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetExtendRightColumn() const
{
	BOOL result;
	GetProperty(0x49, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetExtendRightColumn(BOOL propVal)
{
	SetProperty(0x49, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetPartialRightColumn() const
{
	BOOL result;
	GetProperty(0x9b, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetPartialRightColumn(BOOL propVal)
{
	SetProperty(0x9b, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetAnchorRightColumn() const
{
	BOOL result;
	GetProperty(0x9e, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAnchorRightColumn(BOOL propVal)
{
	SetProperty(0x9e, VT_BOOL, propVal);
}

VARIANT CTrueDBGridCtrl::GetFirstRow() const
{
	VARIANT result;
	GetProperty(0x16, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetFirstRow(const VARIANT& propVal)
{
	SetProperty(0x16, VT_VARIANT, &propVal);
}

COleFont CTrueDBGridCtrl::GetHeadFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(0xb, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CTrueDBGridCtrl::SetHeadFont(LPDISPATCH propVal)
{
	SetProperty(0xb, VT_DISPATCH, propVal);
}

COleFont CTrueDBGridCtrl::GetFooterFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x90, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CTrueDBGridCtrl::SetFooterFont(LPDISPATCH propVal)
{
	SetProperty(0x90, VT_DISPATCH, propVal);
}

float CTrueDBGridCtrl::GetHeadLines() const
{
	float result;
	GetProperty(0xc, VT_R4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetHeadLines(float propVal)
{
	SetProperty(0xc, VT_R4, propVal);
}

float CTrueDBGridCtrl::GetFootLines() const
{
	float result;
	GetProperty(0x91, VT_R4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetFootLines(float propVal)
{
	SetProperty(0x91, VT_R4, propVal);
}

OLE_HANDLE CTrueDBGridCtrl::GetHWnd() const
{
	OLE_HANDLE result;
	GetProperty(DISPID_HWND, VT_I4, (void*)&result);
	return result;
}

long CTrueDBGridCtrl::GetHWndEditor() const
{
	long result;
	GetProperty(0x28, VT_I4, (void*)&result);
	return result;
}

BOOL CTrueDBGridCtrl::GetMarqueeUnique() const
{
	BOOL result;
	GetProperty(0x4a, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetMarqueeUnique(BOOL propVal)
{
	SetProperty(0x4a, VT_BOOL, propVal);
}

long CTrueDBGridCtrl::GetMarqueeStyle() const
{
	long result;
	GetProperty(0x4b, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetMarqueeStyle(long propVal)
{
	SetProperty(0x4b, VT_I4, propVal);
}

BOOL CTrueDBGridCtrl::GetRecordSelectors() const
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetRecordSelectors(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

float CTrueDBGridCtrl::GetRecordSelectorWidth() const
{
	float result;
	GetProperty(0xcf, VT_R4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetRecordSelectorWidth(float propVal)
{
	SetProperty(0xcf, VT_R4, propVal);
}

short CTrueDBGridCtrl::GetRow() const
{
	short result;
	GetProperty(0xe, VT_I2, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetRow(short propVal)
{
	SetProperty(0xe, VT_I2, propVal);
}

long CTrueDBGridCtrl::GetRowDividerStyle() const
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetRowDividerStyle(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

float CTrueDBGridCtrl::GetRowHeight() const
{
	float result;
	GetProperty(0x10, VT_R4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetRowHeight(float propVal)
{
	SetProperty(0x10, VT_R4, propVal);
}

long CTrueDBGridCtrl::GetScrollBars() const
{
	long result;
	GetProperty(0x20, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetScrollBars(long propVal)
{
	SetProperty(0x20, VT_I4, propVal);
}

long CTrueDBGridCtrl::GetSelLength() const
{
	long result;
	GetProperty(0x41, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetSelLength(long propVal)
{
	SetProperty(0x41, VT_I4, propVal);
}

long CTrueDBGridCtrl::GetSelStart() const
{
	long result;
	GetProperty(0x42, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetSelStart(long propVal)
{
	SetProperty(0x42, VT_I4, propVal);
}

CString CTrueDBGridCtrl::GetSelText() const
{
	CString result;
	GetProperty(0x43, VT_BSTR, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetSelText(LPCTSTR propVal)
{
	SetProperty(0x43, VT_BSTR, propVal);
}

short CTrueDBGridCtrl::GetSelStartCol() const
{
	short result;
	GetProperty(0x11, VT_I2, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetSelStartCol(short propVal)
{
	SetProperty(0x11, VT_I2, propVal);
}

short CTrueDBGridCtrl::GetSelEndCol() const
{
	short result;
	GetProperty(0x12, VT_I2, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetSelEndCol(short propVal)
{
	SetProperty(0x12, VT_I2, propVal);
}

short CTrueDBGridCtrl::GetSplit() const
{
	short result;
	GetProperty(0x2b, VT_I2, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetSplit(short propVal)
{
	SetProperty(0x2b, VT_I2, propVal);
}

short CTrueDBGridCtrl::GetVisibleCols() const
{
	short result;
	GetProperty(0x21, VT_I2, (void*)&result);
	return result;
}

short CTrueDBGridCtrl::GetVisibleRows() const
{
	short result;
	GetProperty(0x13, VT_I2, (void*)&result);
	return result;
}

OLE_COLOR CTrueDBGridCtrl::GetBackColor() const
{
	OLE_COLOR result;
	GetProperty(DISPID_BACKCOLOR, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetBackColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_BACKCOLOR, VT_I4, propVal);
}

OLE_COLOR CTrueDBGridCtrl::GetForeColor() const
{
	OLE_COLOR result;
	GetProperty(DISPID_FORECOLOR, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetForeColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_FORECOLOR, VT_I4, propVal);
}

CString CTrueDBGridCtrl::GetCaption() const
{
	CString result;
	GetProperty(DISPID_CAPTION, VT_BSTR, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetCaption(LPCTSTR propVal)
{
	SetProperty(DISPID_CAPTION, VT_BSTR, propVal);
}

COleFont CTrueDBGridCtrl::GetFont() const
{
	LPDISPATCH pDispatch;
	GetProperty(DISPID_FONT, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CTrueDBGridCtrl::SetFont(LPDISPATCH propVal)
{
	SetProperty(DISPID_FONT, VT_DISPATCH, propVal);
}

short CTrueDBGridCtrl::GetLeftCol() const
{
	short result;
	GetProperty(0x17, VT_I2, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetLeftCol(short propVal)
{
	SetProperty(0x17, VT_I2, propVal);
}

BOOL CTrueDBGridCtrl::GetAllowArrows() const
{
	BOOL result;
	GetProperty(0x2f, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAllowArrows(BOOL propVal)
{
	SetProperty(0x2f, VT_BOOL, propVal);
}

long CTrueDBGridCtrl::GetExposeCellMode() const
{
	long result;
	GetProperty(0x30, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetExposeCellMode(long propVal)
{
	SetProperty(0x30, VT_I4, propVal);
}

BOOL CTrueDBGridCtrl::GetTabAcrossSplits() const
{
	BOOL result;
	GetProperty(0x31, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetTabAcrossSplits(BOOL propVal)
{
	SetProperty(0x31, VT_BOOL, propVal);
}

long CTrueDBGridCtrl::GetTabAction() const
{
	long result;
	GetProperty(0x32, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetTabAction(long propVal)
{
	SetProperty(0x32, VT_I4, propVal);
}

BOOL CTrueDBGridCtrl::GetWrapCellPointer() const
{
	BOOL result;
	GetProperty(0x33, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetWrapCellPointer(BOOL propVal)
{
	SetProperty(0x33, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetWrapRowPointer() const
{
	BOOL result;
	GetProperty(0xea, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetWrapRowPointer(BOOL propVal)
{
	SetProperty(0xea, VT_BOOL, propVal);
}

CStyleDisp CTrueDBGridCtrl::GetStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x2c, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetStyle(LPDISPATCH propVal)
{
	SetProperty(0x2c, VT_DISPATCH, propVal);
}

CStyleDisp CTrueDBGridCtrl::GetHeadingStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x2d, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetHeadingStyle(LPDISPATCH propVal)
{
	SetProperty(0x2d, VT_DISPATCH, propVal);
}

CStyleDisp CTrueDBGridCtrl::GetFooterStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x92, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetFooterStyle(LPDISPATCH propVal)
{
	SetProperty(0x92, VT_DISPATCH, propVal);
}

CStyleDisp CTrueDBGridCtrl::GetEditorStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x2e, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetEditorStyle(LPDISPATCH propVal)
{
	SetProperty(0x2e, VT_DISPATCH, propVal);
}

CStyleDisp CTrueDBGridCtrl::GetInactiveStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x34, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetInactiveStyle(LPDISPATCH propVal)
{
	SetProperty(0x34, VT_DISPATCH, propVal);
}

CStyleDisp CTrueDBGridCtrl::GetSelectedStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x35, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetSelectedStyle(LPDISPATCH propVal)
{
	SetProperty(0x35, VT_DISPATCH, propVal);
}

CStyleDisp CTrueDBGridCtrl::GetCaptionStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x36, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetCaptionStyle(LPDISPATCH propVal)
{
	SetProperty(0x36, VT_DISPATCH, propVal);
}

CStyleDisp CTrueDBGridCtrl::GetHighlightRowStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x78, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetHighlightRowStyle(LPDISPATCH propVal)
{
	SetProperty(0x78, VT_DISPATCH, propVal);
}

CStyleDisp CTrueDBGridCtrl::GetEvenRowStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x7a, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetEvenRowStyle(LPDISPATCH propVal)
{
	SetProperty(0x7a, VT_DISPATCH, propVal);
}

CStyleDisp CTrueDBGridCtrl::GetOddRowStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0x7b, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetOddRowStyle(LPDISPATCH propVal)
{
	SetProperty(0x7b, VT_DISPATCH, propVal);
}

unsigned long CTrueDBGridCtrl::GetHeadBackColor() const
{
	unsigned long result;
	GetProperty(0x37, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetHeadBackColor(unsigned long propVal)
{
	SetProperty(0x37, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetHeadForeColor() const
{
	unsigned long result;
	GetProperty(0x38, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetHeadForeColor(unsigned long propVal)
{
	SetProperty(0x38, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetFooterBackColor() const
{
	unsigned long result;
	GetProperty(0x93, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetFooterBackColor(unsigned long propVal)
{
	SetProperty(0x93, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetFooterForeColor() const
{
	unsigned long result;
	GetProperty(0x94, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetFooterForeColor(unsigned long propVal)
{
	SetProperty(0x94, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetEditBackColor() const
{
	unsigned long result;
	GetProperty(0x39, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetEditBackColor(unsigned long propVal)
{
	SetProperty(0x39, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetEditForeColor() const
{
	unsigned long result;
	GetProperty(0x3a, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetEditForeColor(unsigned long propVal)
{
	SetProperty(0x3a, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetInactiveBackColor() const
{
	unsigned long result;
	GetProperty(0x3b, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetInactiveBackColor(unsigned long propVal)
{
	SetProperty(0x3b, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetInactiveForeColor() const
{
	unsigned long result;
	GetProperty(0x3c, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetInactiveForeColor(unsigned long propVal)
{
	SetProperty(0x3c, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetSelectedBackColor() const
{
	unsigned long result;
	GetProperty(0x3d, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetSelectedBackColor(unsigned long propVal)
{
	SetProperty(0x3d, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetSelectedForeColor() const
{
	unsigned long result;
	GetProperty(0x3e, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetSelectedForeColor(unsigned long propVal)
{
	SetProperty(0x3e, VT_I4, propVal);
}

long CTrueDBGridCtrl::GetApproxCount() const
{
	long result;
	GetProperty(0x51, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetApproxCount(long propVal)
{
	SetProperty(0x51, VT_I4, propVal);
}

CString CTrueDBGridCtrl::GetErrorText() const
{
	CString result;
	GetProperty(0x52, VT_BSTR, (void*)&result);
	return result;
}

long CTrueDBGridCtrl::GetAddNewMode() const
{
	long result;
	GetProperty(0x54, VT_I4, (void*)&result);
	return result;
}

BOOL CTrueDBGridCtrl::GetAllowColSelect() const
{
	BOOL result;
	GetProperty(0x56, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAllowColSelect(BOOL propVal)
{
	SetProperty(0x56, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetAllowColMove() const
{
	BOOL result;
	GetProperty(0x57, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAllowColMove(BOOL propVal)
{
	SetProperty(0x57, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetAllowRowSelect() const
{
	BOOL result;
	GetProperty(0x58, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAllowRowSelect(BOOL propVal)
{
	SetProperty(0x58, VT_BOOL, propVal);
}

VARIANT CTrueDBGridCtrl::GetPictureCurrentRow() const
{
	VARIANT result;
	GetProperty(0x95, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetPictureCurrentRow(const VARIANT& propVal)
{
	SetProperty(0x95, VT_VARIANT, &propVal);
}

VARIANT CTrueDBGridCtrl::GetPictureModifiedRow() const
{
	VARIANT result;
	GetProperty(0x96, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetPictureModifiedRow(const VARIANT& propVal)
{
	SetProperty(0x96, VT_VARIANT, &propVal);
}

VARIANT CTrueDBGridCtrl::GetPictureAddnewRow() const
{
	VARIANT result;
	GetProperty(0x97, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetPictureAddnewRow(const VARIANT& propVal)
{
	SetProperty(0x97, VT_VARIANT, &propVal);
}

VARIANT CTrueDBGridCtrl::GetPictureStandardRow() const
{
	VARIANT result;
	GetProperty(0xb0, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetPictureStandardRow(const VARIANT& propVal)
{
	SetProperty(0xb0, VT_VARIANT, &propVal);
}

VARIANT CTrueDBGridCtrl::GetPictureHeaderRow() const
{
	VARIANT result;
	GetProperty(0xb2, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetPictureHeaderRow(const VARIANT& propVal)
{
	SetProperty(0xb2, VT_VARIANT, &propVal);
}

VARIANT CTrueDBGridCtrl::GetPictureFooterRow() const
{
	VARIANT result;
	GetProperty(0xb3, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetPictureFooterRow(const VARIANT& propVal)
{
	SetProperty(0xb3, VT_VARIANT, &propVal);
}

VARIANT CTrueDBGridCtrl::GetMouseIcon() const
{
	VARIANT result;
	GetProperty(0xa3, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetMouseIcon(const VARIANT& propVal)
{
	SetProperty(0xa3, VT_VARIANT, &propVal);
}

long CTrueDBGridCtrl::GetMousePointer() const
{
	long result;
	GetProperty(0xa4, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetMousePointer(long propVal)
{
	SetProperty(0xa4, VT_I4, propVal);
}

LPUNKNOWN CTrueDBGridCtrl::GetISVServices() const
{
	LPUNKNOWN result;
	GetProperty(0x55, VT_UNKNOWN, (void*)&result);
	return result;
}

CString CTrueDBGridCtrl::GetText() const
{
	CString result;
	GetProperty(0x0, VT_BSTR, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetText(LPCTSTR propVal)
{
	SetProperty(0x0, VT_BSTR, propVal);
}

CString CTrueDBGridCtrl::GetLayoutName() const
{
	CString result;
	GetProperty(0x5c, VT_BSTR, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetLayoutName(LPCTSTR propVal)
{
	SetProperty(0x5c, VT_BSTR, propVal);
}

CString CTrueDBGridCtrl::GetLayoutFileName() const
{
	CString result;
	GetProperty(0x5d, VT_BSTR, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetLayoutFileName(LPCTSTR propVal)
{
	SetProperty(0x5d, VT_BSTR, propVal);
}

CString CTrueDBGridCtrl::GetLayoutURL() const
{
	CString result;
	GetProperty(0xb1, VT_BSTR, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetLayoutURL(LPCTSTR propVal)
{
	SetProperty(0xb1, VT_BSTR, propVal);
}

long CTrueDBGridCtrl::GetMultipleLines() const
{
	long result;
	GetProperty(0x61, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetMultipleLines(long propVal)
{
	SetProperty(0x61, VT_I4, propVal);
}

LPDISPATCH CTrueDBGridCtrl::GetArray() const
{
	LPDISPATCH result;
	GetProperty(0x5e, VT_DISPATCH, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetArray(LPDISPATCH propVal)
{
	SetProperty(0x5e, VT_DISPATCH, propVal);
}

BOOL CTrueDBGridCtrl::GetEmptyRows() const
{
	BOOL result;
	GetProperty(0x5f, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetEmptyRows(BOOL propVal)
{
	SetProperty(0x5f, VT_BOOL, propVal);
}

long CTrueDBGridCtrl::GetCellTips() const
{
	long result;
	GetProperty(0x60, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetCellTips(long propVal)
{
	SetProperty(0x60, VT_I4, propVal);
}

float CTrueDBGridCtrl::GetVScrollWidth() const
{
	float result;
	GetProperty(0x70, VT_R4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetVScrollWidth(float propVal)
{
	SetProperty(0x70, VT_R4, propVal);
}

float CTrueDBGridCtrl::GetHScrollHeight() const
{
	float result;
	GetProperty(0x71, VT_R4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetHScrollHeight(float propVal)
{
	SetProperty(0x71, VT_R4, propVal);
}

BOOL CTrueDBGridCtrl::GetBof() const
{
	BOOL result;
	GetProperty(0x6b, VT_BOOL, (void*)&result);
	return result;
}

BOOL CTrueDBGridCtrl::GetEof() const
{
	BOOL result;
	GetProperty(0x6c, VT_BOOL, (void*)&result);
	return result;
}

BOOL CTrueDBGridCtrl::GetFetchRowStyle() const
{
	BOOL result;
	GetProperty(0x79, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetFetchRowStyle(BOOL propVal)
{
	SetProperty(0x79, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetAlternatingRowStyle() const
{
	BOOL result;
	GetProperty(0x7c, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAlternatingRowStyle(BOOL propVal)
{
	SetProperty(0x7c, VT_BOOL, propVal);
}

float CTrueDBGridCtrl::GetCellTipsWidth() const
{
	float result;
	GetProperty(0x7d, VT_R4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetCellTipsWidth(float propVal)
{
	SetProperty(0x7d, VT_R4, propVal);
}

long CTrueDBGridCtrl::GetCellTipsDelay() const
{
	long result;
	GetProperty(0x7e, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetCellTipsDelay(long propVal)
{
	SetProperty(0x7e, VT_I4, propVal);
}

BOOL CTrueDBGridCtrl::GetInsertMode() const
{
	BOOL result;
	GetProperty(0x98, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetInsertMode(BOOL propVal)
{
	SetProperty(0x98, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetTransparentRowPictures() const
{
	BOOL result;
	GetProperty(0x99, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetTransparentRowPictures(BOOL propVal)
{
	SetProperty(0x99, VT_BOOL, propVal);
}

long CTrueDBGridCtrl::GetMultiSelect() const
{
	long result;
	GetProperty(0x84, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetMultiSelect(long propVal)
{
	SetProperty(0x84, VT_I4, propVal);
}

CString CTrueDBGridCtrl::GetDataMember() const
{
	CString result;
	GetProperty(0x9c, VT_BSTR, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetDataMember(LPCTSTR propVal)
{
	SetProperty(0x9c, VT_BSTR, propVal);
}

long CTrueDBGridCtrl::GetOLEDragMode() const
{
	long result;
	GetProperty(0x9f, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetOLEDragMode(long propVal)
{
	SetProperty(0x9f, VT_I4, propVal);
}

long CTrueDBGridCtrl::GetOLEDropMode() const
{
	long result;
	GetProperty(0xa0, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetOLEDropMode(long propVal)
{
	SetProperty(0xa0, VT_I4, propVal);
}

BOOL CTrueDBGridCtrl::GetExportEOF() const
{
	BOOL result;
	GetProperty(0xae, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetExportEOF(BOOL propVal)
{
	SetProperty(0xae, VT_BOOL, propVal);
}

VARIANT CTrueDBGridCtrl::GetExportNextBookmark() const
{
	VARIANT result;
	GetProperty(0xaf, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetExportNextBookmark(const VARIANT& propVal)
{
	SetProperty(0xaf, VT_VARIANT, &propVal);
}

short CTrueDBGridCtrl::GetBands() const
{
	short result;
	GetProperty(0xb6, VT_I2, (void*)&result);
	return result;
}

long CTrueDBGridCtrl::GetDataView() const
{
	long result;
	GetProperty(0xbb, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetDataView(long propVal)
{
	SetProperty(0xbb, VT_I4, propVal);
}

CString CTrueDBGridCtrl::GetGroupByCaption() const
{
	CString result;
	GetProperty(0xc2, VT_BSTR, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetGroupByCaption(LPCTSTR propVal)
{
	SetProperty(0xc2, VT_BSTR, propVal);
}

long CTrueDBGridCtrl::GetAnimateWindow() const
{
	long result;
	GetProperty(0xbd, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAnimateWindow(long propVal)
{
	SetProperty(0xbd, VT_I4, propVal);
}

long CTrueDBGridCtrl::GetAnimateWindowDirection() const
{
	long result;
	GetProperty(0xbe, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAnimateWindowDirection(long propVal)
{
	SetProperty(0xbe, VT_I4, propVal);
}

long CTrueDBGridCtrl::GetAnimateWindowTime() const
{
	long result;
	GetProperty(0xbf, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAnimateWindowTime(long propVal)
{
	SetProperty(0xbf, VT_I4, propVal);
}

long CTrueDBGridCtrl::GetAnimateWindowClose() const
{
	long result;
	GetProperty(0xc0, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetAnimateWindowClose(long propVal)
{
	SetProperty(0xc0, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetDeadAreaBackColor() const
{
	unsigned long result;
	GetProperty(0xc4, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetDeadAreaBackColor(unsigned long propVal)
{
	SetProperty(0xc4, VT_I4, propVal);
}

BOOL CTrueDBGridCtrl::GetScrollTrack() const
{
	BOOL result;
	GetProperty(0xc6, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetScrollTrack(BOOL propVal)
{
	SetProperty(0xc6, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetScrollTips() const
{
	BOOL result;
	GetProperty(0xc9, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetScrollTips(BOOL propVal)
{
	SetProperty(0xc9, VT_BOOL, propVal);
}

unsigned long CTrueDBGridCtrl::GetRowDividerColor() const
{
	unsigned long result;
	GetProperty(0xc7, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetRowDividerColor(unsigned long propVal)
{
	SetProperty(0xc7, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetRowSubDividerColor() const
{
	unsigned long result;
	GetProperty(0xc8, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetRowSubDividerColor(unsigned long propVal)
{
	SetProperty(0xc8, VT_I4, propVal);
}

long CTrueDBGridCtrl::GetDirectionAfterEnter() const
{
	long result;
	GetProperty(0xca, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetDirectionAfterEnter(long propVal)
{
	SetProperty(0xca, VT_I4, propVal);
}

long CTrueDBGridCtrl::GetDirectionAfterTab() const
{
	long result;
	GetProperty(0xeb, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetDirectionAfterTab(long propVal)
{
	SetProperty(0xeb, VT_I4, propVal);
}

BOOL CTrueDBGridCtrl::GetRightToLeft() const
{
	BOOL result;
	GetProperty(0xfffffd9d, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetRightToLeft(BOOL propVal)
{
	SetProperty(0xfffffd9d, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetFilterActive() const
{
	BOOL result;
	GetProperty(0xcc, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetFilterActive(BOOL propVal)
{
	SetProperty(0xcc, VT_BOOL, propVal);
}

BOOL CTrueDBGridCtrl::GetFilterBar() const
{
	BOOL result;
	GetProperty(0xd0, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetFilterBar(BOOL propVal)
{
	SetProperty(0xd0, VT_BOOL, propVal);
}

long CTrueDBGridCtrl::GetMaxRows() const
{
	long result;
	GetProperty(0xce, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetMaxRows(long propVal)
{
	SetProperty(0xce, VT_I4, propVal);
}

CStyleDisp CTrueDBGridCtrl::GetRecordSelectorStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0xcb, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetRecordSelectorStyle(LPDISPATCH propVal)
{
	SetProperty(0xcb, VT_DISPATCH, propVal);
}

short CTrueDBGridCtrl::GetDestinationSplit() const
{
	short result;
	GetProperty(0xd2, VT_I2, (void*)&result);
	return result;
}

VARIANT CTrueDBGridCtrl::GetDestinationRow() const
{
	VARIANT result;
	GetProperty(0xd3, VT_VARIANT, (void*)&result);
	return result;
}

short CTrueDBGridCtrl::GetDestinationCol() const
{
	short result;
	GetProperty(0xd4, VT_I2, (void*)&result);
	return result;
}

VARIANT CTrueDBGridCtrl::GetPictureFilterBar() const
{
	VARIANT result;
	GetProperty(0xd5, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetPictureFilterBar(const VARIANT& propVal)
{
	SetProperty(0xd5, VT_VARIANT, &propVal);
}

CStyleDisp CTrueDBGridCtrl::GetFilterBarStyle() const
{
	LPDISPATCH pDispatch;
	GetProperty(0xd6, VT_DISPATCH, (void*)&pDispatch);
	return CStyleDisp(pDispatch);
}

void CTrueDBGridCtrl::SetFilterBarStyle(LPDISPATCH propVal)
{
	SetProperty(0xd6, VT_DISPATCH, propVal);
}

VARIANT CTrueDBGridCtrl::GetChildGrid() const
{
	VARIANT result;
	GetProperty(0xd7, VT_VARIANT, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetChildGrid(const VARIANT& propVal)
{
	SetProperty(0xd7, VT_VARIANT, &propVal);
}

BOOL CTrueDBGridCtrl::GetSelRange() const
{
	BOOL result;
	GetProperty(0xd8, VT_BOOL, (void*)&result);
	return result;
}

BOOL CTrueDBGridCtrl::GetSpringMode() const
{
	BOOL result;
	GetProperty(0xd9, VT_BOOL, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetSpringMode(BOOL propVal)
{
	SetProperty(0xd9, VT_BOOL, propVal);
}

float CTrueDBGridCtrl::GetViewColumnCaptionWidth() const
{
	float result;
	GetProperty(0xdc, VT_R4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetViewColumnCaptionWidth(float propVal)
{
	SetProperty(0xdc, VT_R4, propVal);
}

float CTrueDBGridCtrl::GetViewColumnWidth() const
{
	float result;
	GetProperty(0xdd, VT_R4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetViewColumnWidth(float propVal)
{
	SetProperty(0xdd, VT_R4, propVal);
}

unsigned long CTrueDBGridCtrl::GetExpandColor() const
{
	unsigned long result;
	GetProperty(0xde, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetExpandColor(unsigned long propVal)
{
	SetProperty(0xde, VT_I4, propVal);
}

unsigned long CTrueDBGridCtrl::GetCollapseColor() const
{
	unsigned long result;
	GetProperty(0xdf, VT_I4, (void*)&result);
	return result;
}

void CTrueDBGridCtrl::SetCollapseColor(unsigned long propVal)
{
	SetProperty(0xdf, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CTrueDBGridCtrl operations

void CTrueDBGridCtrl::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

CColumns CTrueDBGridCtrl::GetColumns()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x8, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CColumns(pDispatch);
}

CSplits CTrueDBGridCtrl::GetSplits()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x23, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CSplits(pDispatch);
}

CStyles CTrueDBGridCtrl::GetStyles()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x26, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CStyles(pDispatch);
}

CSelBookmarks CTrueDBGridCtrl::GetSelBookmarks()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x15, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CSelBookmarks(pDispatch);
}

short CTrueDBGridCtrl::ColContaining(float X)
{
	short result;
	static BYTE parms[] =
		VTS_R4;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		X);
	return result;
}

VARIANT CTrueDBGridCtrl::GetBookmark(long RowNum)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		RowNum);
	return result;
}

void CTrueDBGridCtrl::ReBind()
{
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

VARIANT CTrueDBGridCtrl::RowBookmark(short RowNum)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		RowNum);
	return result;
}

short CTrueDBGridCtrl::RowContaining(float Y)
{
	short result;
	static BYTE parms[] =
		VTS_R4;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		Y);
	return result;
}

float CTrueDBGridCtrl::RowTop(short RowNum)
{
	float result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_R4, (void*)&result, parms,
		RowNum);
	return result;
}

void CTrueDBGridCtrl::Scroll(long Cols, long Rows)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Cols, Rows);
}

void CTrueDBGridCtrl::Refresh()
{
	InvokeHelper(DISPID_REFRESH, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

CPicture CTrueDBGridCtrl::CaptureImage()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CPicture(pDispatch);
}

void CTrueDBGridCtrl::AddCellStyle(short Condition, const VARIANT& Style)
{
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition, &Style);
}

void CTrueDBGridCtrl::AddRegexCellStyle(short Condition, const VARIANT& Style, LPCTSTR Regex)
{
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT VTS_BSTR;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition, &Style, Regex);
}

void CTrueDBGridCtrl::ClearCellStyle(short Condition)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x4e, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition);
}

void CTrueDBGridCtrl::ClearRegexCellStyle(short Condition, const VARIANT& Regex)
{
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT;
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Condition, &Regex);
}

void CTrueDBGridCtrl::ClearSelCols()
{
	InvokeHelper(0x4c, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CTrueDBGridCtrl::ClearFields()
{
	InvokeHelper(0x4d, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CTrueDBGridCtrl::HoldFields()
{
	InvokeHelper(0x59, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

short CTrueDBGridCtrl::SplitContaining(float X, float Y)
{
	short result;
	static BYTE parms[] =
		VTS_R4 VTS_R4;
	InvokeHelper(0x53, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		X, Y);
	return result;
}

long CTrueDBGridCtrl::PointAt(float X, float Y)
{
	long result;
	static BYTE parms[] =
		VTS_R4 VTS_R4;
	InvokeHelper(0xa5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		X, Y);
	return result;
}

void CTrueDBGridCtrl::PostMsg(short MsgId)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5a, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		MsgId);
}

void CTrueDBGridCtrl::Update()
{
	InvokeHelper(0x5b, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CTrueDBGridCtrl::MoveRelative(long offset, const VARIANT& Bookmark)
{
	static BYTE parms[] =
		VTS_I4 VTS_VARIANT;
	InvokeHelper(0x66, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		offset, &Bookmark);
}

void CTrueDBGridCtrl::MoveFirst()
{
	InvokeHelper(0x67, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CTrueDBGridCtrl::MoveLast()
{
	InvokeHelper(0x68, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CTrueDBGridCtrl::MoveNext()
{
	InvokeHelper(0x69, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CTrueDBGridCtrl::MovePrevious()
{
	InvokeHelper(0x6a, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CTrueDBGridCtrl::Delete()
{
	InvokeHelper(0x6d, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CTrueDBGridCtrl::Close(const VARIANT& Repaint)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x6e, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Repaint);
}

void CTrueDBGridCtrl::ReOpen(const VARIANT& Bookmark)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x6f, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Bookmark);
}

void CTrueDBGridCtrl::LoadLayout()
{
	InvokeHelper(0x76, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

CLayouts CTrueDBGridCtrl::GetLayouts()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x7f, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CLayouts(pDispatch);
}

BOOL CTrueDBGridCtrl::CellContaining(float X, float Y, long* RowAt, short* ColAt)
{
	BOOL result;
	static BYTE parms[] =
		VTS_R4 VTS_R4 VTS_PI4 VTS_PI2;
	InvokeHelper(0x89, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		X, Y, RowAt, ColAt);
	return result;
}

void CTrueDBGridCtrl::RefreshRow(const VARIANT& Bookmark)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x44, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Bookmark);
}

void CTrueDBGridCtrl::RefreshCol(const VARIANT& Col)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x45, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Col);
}

void CTrueDBGridCtrl::RefetchRow(const VARIANT& Bookmark)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x8a, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Bookmark);
}

void CTrueDBGridCtrl::RefetchCol(const VARIANT& Col)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x8b, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Col);
}

void CTrueDBGridCtrl::OLEDrag()
{
	InvokeHelper(0xa1, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

short CTrueDBGridCtrl::IsSelected(const VARIANT& Bookmark)
{
	short result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0xa2, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		&Bookmark);
	return result;
}

void CTrueDBGridCtrl::ExportToFile(LPCTSTR outPath, BOOL append, const VARIANT& selector, const VARIANT& tableWidth)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xaa, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		outPath, append, &selector, &tableWidth);
}

void CTrueDBGridCtrl::ExportBegin(const VARIANT& Bookmark)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0xab, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Bookmark);
}

void CTrueDBGridCtrl::ExportRows(LPCTSTR outPath, BOOL append, long Rows, const VARIANT& tableWidth)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL VTS_I4 VTS_VARIANT;
	InvokeHelper(0xac, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		outPath, append, Rows, &tableWidth);
}

void CTrueDBGridCtrl::ExportEnd()
{
	InvokeHelper(0xad, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}

void CTrueDBGridCtrl::ExportToDelimitedFile(LPCTSTR outPath, const VARIANT& selector, const VARIANT& delim, const VARIANT& prefix, const VARIANT& suffix, const VARIANT& headers)
{
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xa9, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		outPath, &selector, &delim, &prefix, &suffix, &headers);
}

CPrintInfos CTrueDBGridCtrl::GetPrintInfos()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xb4, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CPrintInfos(pDispatch);
}

CPrintInfo1 CTrueDBGridCtrl::GetPrintInfo()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xb5, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CPrintInfo1(pDispatch);
}

CErrors CTrueDBGridCtrl::GetErrors()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xd1, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CErrors(pDispatch);
}

short CTrueDBGridCtrl::GetBand(short ColumnIndex)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xb7, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		ColumnIndex);
	return result;
}

BOOL CTrueDBGridCtrl::RowExpanded(short Band)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xb8, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Band);
	return result;
}

void CTrueDBGridCtrl::CollapseBand(short Band)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xb9, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Band);
}

void CTrueDBGridCtrl::ExpandBand(short Band)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xba, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		Band);
}

CGroupColumns CTrueDBGridCtrl::GetGroupColumns()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xc3, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, nullptr);
	return CGroupColumns(pDispatch);
}
