#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CValueItemDisp wrapper class

class CValueItemDisp : public COleDispatchDriver
{
	public:
	CValueItemDisp()
	{
	} // Calls COleDispatchDriver default constructor
	CValueItemDisp(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	CValueItemDisp(const CValueItemDisp& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
	public:
	VARIANT GetValue() const;
	void SetValue(const VARIANT&);
	VARIANT GetDisplayValue() const;
	void SetDisplayValue(const VARIANT&);

	// Operations
	public:
};
