// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "stdafx.h"
#include "valueitems.h"

// Dispatch interfaces referenced by this interface
#include "ValueItemDisp.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CValueItems properties

long CValueItems::GetCount() const
{
	long result;
	GetProperty(0x7d2, VT_I4, (void*)&result);
	return result;
}

long CValueItems::GetPresentation() const
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CValueItems::SetPresentation(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

BOOL CValueItems::GetTranslate() const
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CValueItems::SetTranslate(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CValueItems::GetValidate() const
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CValueItems::SetValidate(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CValueItems::GetCycleOnClick() const
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CValueItems::SetCycleOnClick(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

short CValueItems::GetMaxComboItems() const
{
	short result;
	GetProperty(0x6, VT_I2, (void*)&result);
	return result;
}

void CValueItems::SetMaxComboItems(short propVal)
{
	SetProperty(0x6, VT_I2, propVal);
}

short CValueItems::GetDefaultItem() const
{
	short result;
	GetProperty(0x7, VT_I2, (void*)&result);
	return result;
}

void CValueItems::SetDefaultItem(short propVal)
{
	SetProperty(0x7, VT_I2, propVal);
}

BOOL CValueItems::GetAnnotatePicture() const
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CValueItems::SetAnnotatePicture(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CValueItems::GetMatchCase() const
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CValueItems::SetMatchCase(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CValueItems operations

LPUNKNOWN CValueItems::Get_NewEnum()
{
	LPUNKNOWN result;
	InvokeHelper(0xfffffffc, DISPATCH_PROPERTYGET, VT_UNKNOWN, (void*)&result, nullptr);
	return result;
}

CValueItemDisp CValueItems::GetItem(const VARIANT& Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		&Index);
	return CValueItemDisp(pDispatch);
}

void CValueItems::Add(LPDISPATCH vitem)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x7d5, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		vitem);
}

void CValueItems::Remove(const VARIANT& Index)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x7d6, DISPATCH_METHOD, VT_EMPTY, nullptr, parms,
		&Index);
}

void CValueItems::Clear()
{
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, nullptr, nullptr);
}
