#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

// Dispatch interfaces referenced by this interface
class CValueItemDisp;

/////////////////////////////////////////////////////////////////////////////
// CValueItems wrapper class

class CValueItems : public COleDispatchDriver
{
	public:
	CValueItems()
	{
	} // Calls COleDispatchDriver default constructor
	CValueItems(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch)
	{
	}

	CValueItems(const CValueItems& dispatchSrc) : COleDispatchDriver(dispatchSrc)
	{
	}

	// Attributes
	public:
	long GetCount() const;
	long GetPresentation() const;
	void SetPresentation(long);
	BOOL GetTranslate() const;
	void SetTranslate(BOOL);
	BOOL GetValidate() const;
	void SetValidate(BOOL);
	BOOL GetCycleOnClick() const;
	void SetCycleOnClick(BOOL);
	short GetMaxComboItems() const;
	void SetMaxComboItems(short);
	short GetDefaultItem() const;
	void SetDefaultItem(short);
	BOOL GetAnnotatePicture() const;
	void SetAnnotatePicture(BOOL);
	BOOL GetMatchCase() const;
	void SetMatchCase(BOOL);

	// Operations
	public:
	LPUNKNOWN Get_NewEnum();
	CValueItemDisp GetItem(const VARIANT& Index);
	void Add(LPDISPATCH vitem);
	void Remove(const VARIANT& Index);
	void Clear();
};
