//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Navigate.rc

#define IDS_MANAGER_NAVIGATE            5
#define IDS_PANE_VEHICLE                6
#define IDS_MANAGER_VEHICLE             7
#define IDS_PANE_NAVIGATE               8
#define IDS_SETUP                       9
#define IDP_SOCKETS_INIT_FAILED         10
#define IDS_SYSTEM_PHONE                11
#define IDD_CMDPARAM                    12
#define IDS_GRID_MONITOR                13
#define IDS_GRID_MESSAGEWND             14
#define IDI_GPSRECEIVER                 15
#define IDD_MONITOR                     16
#define IDB_ROUTE32                     17
#define IDD_SERIAL                      18
#define IDD_SOCKET                      19
#define IDD_LOGIN                       20
#define IDD_CALL                        21
#define IDB_VEHICLEBN                   22
#define IDB_VEHICLEBW                   23
#define IDD_VEHICLEINFO                 24
#define IDD_MODEM                       25
#define IDB_COMPASS                     26
#define IDB_COMPASSL                    27
#define IDD_PORT                        28
#define IDB_VEHICLE1                    29
#define IDB_VEHICLE2                    30
#define IDB_VEHICLE3                    31
#define IDB_VEHICLE4                    32
#define IDB_PREVIEW                     33
#define IDD_REPLAY                      34
#define IDD_ICON                        35
#define IDD_DATABASE                    36
#define IDD_SPEED                       37
#define IDD_ROUTE                       38
#define IDD_COMMAND                     39
#define IDD_SELECT                      40
#define IDD_NAVINFO                     41
#define IDD_PROXY                       42
#define IDD_MESSAGE                     43
#define IDB_SIGNAL                      44
#define IDI_NAVINFO                     45
#define IDR_MENU_POP                    46
#define IDI_VEHICLE                     47
#define IDD_DISPATCH                    48
#define IDD_SEARCH                      49
#define IDB_ROUTE16                     50
#define IDB_LED                         51
#define IDC_SEND                        1000
#define IDC_ROUTE                       1001
#define IDC_WAYPOINT                    1002
#define IDC_EDIT0                       1003
#define IDC_STATIC0                     1004
#define IDC_EDIT4                       1005
#define IDC_STATIC3                     1006
#define IDC_STATIC4                     1007
#define IDC_COMBO_SELECT                1008
#define IDC_STATIC_DESCRIPTION          1009
#define IDC_DATETIMEPICKER1             1010
#define IDC_DATETIMEPICKER4             1011
#define IDC_DATETIMEPICKER3             1012
#define IDC_DATETIMEPICKER2             1013
#define IDC_SPEED                       1014
#define IDC_TIME                        1015
#define IDC_LEFTLENGTH                  1016
#define IDC_ALTITUDE                    1017
#define IDC_PORT                        1018
#define IDC_ROUTELENGTH                 1019
#define IDC_LEFTLENGTH2                 1020
#define IDC_BAUDRATE                    1021
#define IDC_PARITY                      1022
#define IDC_STOPBITS                    1023
#define IDC_DATABITS                    1024
#define IDC_ROTATEMAP                   1025
#define IDC_SATELITE                    1026
#define IDC_MODEM                       1027
#define IDC_ZONE                        1028
#define IDC_TELEPHONE                   1029
#define IDC_USER                        1030
#define IDC_MSFLEXGRID                  1031
#define IDC_SERVER                      1032
#define IDC_USERNAME                    1033
#define IDC_PASSWORD                    1034
#define IDC_USERLIST                    1035
#define IDC_IVU                         1036
#define IDC_ID                          1037
#define IDC_COMPASS                     1038
#define IDC_TYPECOMBO                   1039
#define IDC_DATEPICKER1                 1040
#define IDC_TIMEPICKER1                 1041
#define IDC_DATEPICKER2                 1042
#define IDC_TIMEPICKER2                 1043
#define IDC_ANCHOR                      1044
#define IDC_SLIDER                      1045
#define IDC_HASHING                     1046
#define IDC_NUMBER                      1047
#define IDC_DIALUP                      1048
#define IDC_HANGUP                      1049
#define IDC_ODBCDSN                     1050
#define IDC_SERVERNAME                  1051
#define IDC_ODBCUID                     1052
#define IDC_ODBCPWD                     1053
#define IDC_SETUP                       1054
#define IDC_EDIT                        1055
#define IDC_IMAGELIST1                  1056
#define IDC_ICON1                       1057
#define IDC_IMAGELIST2                  1058
#define IDC_STATIC2                     1059
#define IDC_ICON2                       1060
#define IDC_STATIC1                     1061
#define IDC_RADIO1                      1062
#define IDC_IMAGELIST3                  1063
#define IDC_RADIO2                      1064
#define IDC_IMAGELIST4                  1065
#define IDC_RADIO3                      1066
#define IDC_ICON3                       1067
#define IDC_EDIT1                       1068
#define IDC_ICON4                       1069
#define IDC_EDIT3                       1070
#define IDC_FIELDCOMBO                  1071
#define IDC_EDIT2                       1072
#define IDC_OPERATERCOMBO               1073
#define IDC_TIMES                       1074
#define IDC_PROXYPWD                    1075
#define IDC_SEARCH                      1076
#define IDC_PROXYDOMAIN                 1077
#define IDC_ALL                         1078
#define IDC_VALUE                       1079
#define IDC_ERASE                       1080
#define IDC_TRACK                       1081
#define IDC_MESSAGE                     1082
#define IDC_COMMAND                     1083
#define IDC_CALL                        1084
#define IDC_VEHICLE                     1085
#define IDC_TRACE                       1086
#define IDC_GROUP                       1087
#define IDC_TILE                        1088
#define IDC_INTERVAL                    1089
#define IDC_CMDLIST                     1090
#define IDC_STATIC_IVUTYPE              1091
#define IDC_AVAILABLE                   1092
#define IDC_BUTTON1                     1093
#define IDC_STATIC_MESSAGE              1094
#define IDC_PROXYUSER                   1095
#define IDC_BUTTON2                     1096
#define IDC_PROXYSERVER                 1097
#define IDC_BUTTON3                     1098
#define IDC_KEY_STRING                  1099
#define IDC_PROXYPORT                   1100
#define IDC_BUTTON4                     1101
#define IDC_PROXY                       1102
#define IDC_NOINTERVAL                  1103
#define IDC_DURATIVERADIO               1104
#define IDC_ONCERADIO                   1105
#define IDC_LIMITLESS                   1106
#define IDC_AUTOIN                      1107
#define IDC_TRACKVEHICLE                1108
#define IDC_DRAWTRACE                   1109
#define IDC_SAVETRACE                   1110
#define ID_MENUITEM_SORT_AESC           32771
#define ID_MENUITEM_SORT_DESC           32772
#define ID_MENUITEM_TRACE_STOP          32773
#define ID_MENUITEM_TRACE               32774
#define ID_MENUITEM_SEARCH              32775
#define ID_MENUITEM_DISPATCH            32776

// Next default values for new objects

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        100
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           1211
#endif
#endif
