//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Mapper.rc
//
#define IDS_NOACTIVELAYER               2
#define IDS_INSERTERROR                 3
#define IDS_NOLAYERTABLE                4
#define IDS_INCONSISTENTTABLE           5
#define IDS_CANNOTOPENTABLE             6
#define IDS_TOOLBAR_STANDARD            7
#define IDS_VIEW_CUSTOMIZE              8
#define IDS_STATUSINFO                  9
#define IDS_VIEWSCALE                   10
#define IDS_VIEWLEVEL                   11
#define IDS_PROGRESSBAR                 12
#define IDS_GEOMNAME                    13
#define IDS_GEOCODE                     14
#define IDS_GEOMID                      15
#define IDS_POINTCOUNT                  16
#define IDS_HANDLEXY                    17
#define IDS_COORDINATE                  18
#define IDS_UNITCOMBO                   19
#define IDP_SOCKETS_INIT_FAILED         20
#define IDD_ABOUTBOX                    21
#define IDS_UNDOWILLBECLEARED           21
#define IDD_MOVE                        22
#define IDS_LOSINGUNDOS                 22
#define IDD_PREFER                      23
#define IDS_NEEDSINGLECLOSEDPATH        23
#define IDB_SPLASH                      24
#define IDR_GRFTYPE                     26
#define IDR_GRFTYPR                     26
#define IDR_GISTYPE                     27
#define IDR_GEOTYPE                     28
#define IDR_ITEM                        29
#define IDD_CREATETABLE                 30
#define IDD_ATLASNEW                    31
#define IDD_REPLACE                     38
#define IDB_GEOMALIGN_SMALL             48
#define IDB_CLASS_VIEW                  52
#define IDB_CLASS_VIEW24                53
#define ID_TOOL_RECTIFYDATUM            57
#define IDP_FAILED_TO_CREATE            59
#define IDR_GRFTYPE_CNTR_IP             60
#define IDP_OLE_INIT_FAILED             61
#define IDR_GISTYPE_CNTR_IP             62
#define IDR_MDBTYPE_CNTR_IP             63
#define IDR_GEOTYPE_CNTR_IP             64
#define IDB_ENDSQUARE                   67
#define IDB_ENDROUND                    68
#define IDB_ENDBUTT                     69
#define IDB_JOINBEVEL                   78
#define IDB_JOINROUND                   79
#define IDB_JOINSQUARE                  80
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILE_LARGE                  114
#define IDB_FILE_SMALL                  115
#define IDR_MAINFRAME                   128
#define IDD_SCALEBAR                    134
#define IDD_PUBLISHTOWEB                139
#define IDD_DIALOG1                     141
#define IDD_DYNAMIC                     141
#define IDD_LEVELBAR                    142
#define IDR_MENU1                       143
#define IDR_POPUP                       143
#define IDC_SCALE                       144
#define IDR_RIBBON                      151
#define IDB_LOGO                        154
#define IDB_HOME_LARGE                  155
#define IDB_HOME_SMALL                  156
#define IDB_GEOGRAPH_SMALL              157
#define IDB_GEOMETRY_SMALL              158
#define IDB_COMBINATION_SMALL           160
#define IDB_BITMAP1                     161
#define IDB_ALIGNMENT                   161
#define IDC_EXCUTE                      162
#define IDB_ARRANGE                     162
#define IDB_DATABASE_SMALL              164
#define IDB_TOPOLOGY_SMALL              165
#define IDB_BITMAP2                     169
#define IDB_PROCESS_LARGE               169
#define IDB_DATABASE_LARGE              170
#define IDB_VIEW_LARGE                  172
#define IDB_GEOGRAPHY_LARGE             173
#define IDB_GEOGRAPH_LARGE              173
#define IDB_VIEW_SMALL                  174
#define IDB_TOPOLOGY_LARGE              175
#define IDB_GEOMETRY_LARGE              177
#define IDD_PATHBUFFER                  180
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDC_ENDSQUARE                   224
#define IDC_ENDROUND                    225
#define IDC_JOINBEVEL                   226
#define IDC_JOINROUND                   227
#define IDC_JOINMITER                   228
#define IDC_ENDBUTT                     239
#define IDC_NEXT                        1000
#define IDC_REPLACE                     1001
#define IDC_REPLACEALL                  1002
#define IDC_PATHPICKER                  1003
#define IDC_UNITCOMBO                   1004
#define IDC_UNITSHOW                    1005
#define IDC_UNIT                        1005
#define IDC_CONTENT                     1006
#define IDC_FILL                        1007
#define IDC_CX                          1008
#define IDC_CY                          1009
#define IDC_GREEKTYPE                   1010
#define IDC_UNDONUMBER                  1011
#define IDC_TOLERANCE                   1012
#define IDC_JOINTOLERANCE               1012
#define IDC_DENSITY                     1013
#define IDC_EQUAL                       1014
#define IDC_TOPOTOLERANCE               1014
#define IDC_CAPSGREEK                   1015
#define IDC_SOURCE                      1016
#define IDC_DESTINATION                 1017
#define IDC_LAYERTREE                   1018
#define IDC_TABLENAME                   1019
#define IDC_CHECK1                      1020
#define IDC_RADIO1                      1021
#define IDC_RADIO2                      1022
#define IDC_VERSION                     1023
#define IDC_MFCLINK1                    1024
#define IDC_EDIT1                       1027
#define IDC_EDIT2                       1028
#define IDC_EDIT3                       1029
#define IDC_EDIT4                       1030
#define IDC_EDIT5                       1031
#define IDC_EDIT6                       1032
#define IDC_UPDATE                      1033
#define IDC_CUSTOM2                     1035
#define IDC_WEBUID                      1036
#define IDC_LEVELMAX                    1037
#define IDC_LEVELMIN                    1038
#define IDC_EXPORTPROPERTY              1039
#define IDC_LEVEL                       1040
#define IDC_BUFFERDELTA                 1041
#define IDC_PARTIAL                     1042
#define IDC_LOCAL                       1043
#define ID_ITEM_ADDAFTER                33000
#define ID_ITEM_ADDIN                   33001
#define ID_ITEM_DELETE                  33002
#define ID_ARRANGE_TOFRONT              33003
#define ID_ARRANGE_TOBACK               33004
#define ID_ARRANGE_FORWARD              33005
#define ID_ARRANGE_BACKWARD             33006
#define ID_TOPOEDGE_REMOVE              33009
#define ID_ITEM_ADDBEFORE               33010
#define ID_EDIT_DUPLICATE               33011
#define ID_EDIT_CLONE                   33012
#define ID_GEOM_LOCK                    33013
#define ID_GEOM_UNLOCK                  33014
#define ID_GEOM_GROUP                   33015
#define ID_VIEW_RULER                   33016
#define ID_GEOM_UNGROUP                 33017
#define ID_FILE_IMPORT                  33018
#define ID_FILE_EXPORT                  33019
#define ID_FILE_DOCSETUP                33020
#define ID_FILE_PREFERENCES             33021
#define ID_MAGNIFY_FITINPAGE            33022
#define ID_VIEW_GRID                    33024
#define ID_VIEW_GUIDES                  33025
#define ID_FILE_REVERT                  33026
#define ID_EDIT_INSERTOLE               33027
#define ID_GEOM_JOIN                    33028
#define ID_GEOM_SPLIT                   33029
#define ID_PATH_REVERSE                 33030
#define ID_EDIT_MOVE                    33031
#define ID_SELECTALL_INVERSE            33032
#define ID_SELECTALL_ALL                33033
#define ID_SELECTALL_AREA               33034
#define ID_SELECTALL_TEXT               33035
#define ID_SELECTALL_MARK               33036
#define ID_SELECTALL_LINE               33037
#define ID_SELECTALL_NONAME             33038
#define ID_SELECTALL_GROUP              33039
#define ID_SELECTALL_DONUT              33040
#define ID_SELECTALL_IMAGE              33041
#define ID_SELECTALL_BEZIER             33042
#define ID_SELECTALL_HASNAME            33043
#define ID_SELECTALL_POLYTEXT           33044
#define ID_SELECTALL_CLIP               33045
#define ID_SELECTALL_MASK               33046
#define ID_SELECTALL_REBEL              33050
#define ID_SELECTALL_WITHNAME           33051
#define ID_SELECTALL_IDENTICAL          33052
#define ID_SELECTALL_SAMESTYLE          33054
#define ID_SELECTALL_SAMESHAPE          33055
#define ID_PATH_DENSIFY                 33057
#define ID_PATH_SIMPLIFY                33058
#define ID_COVERT_BEZIERTOPOLY          33059
#define ID_COVERT_POLYTOBEZIER          33060
#define ID_VIEW_DRAWTOOL                33061
#define ID_LINK_CREATE                  33062
#define ID_LINK_EDIT                    33063
#define ID_LINK_DELETE                  33064
#define ID_RUNTOOL_ZOOMIN               33065
#define ID_RUNTOOL_ZOOMOUT              33066
#define ID_RUNTOOL_INFO                 33067
#define ID_RUNTOOL_PRINT                33068
#define ID_RUNTOOL_PAN                  33069
#define ID_VIEW_MANAGER                 33070
#define ID_FILE_MAPINFO                 33071
#define ID_PATH_BUFFER                  33072
#define ID_SELECTALL_DISCARD            33073
#define ID_GEOM_SETTYPE                 33074
#define ID_GEOM_SETSPOT                 33075
#define ID_GEOM_SETSTYLE                33076
#define ID_GEOM_REGRESS                 33077
#define ID_ANNO_TOTEXT                  33078
#define ID_MAGNIFY_FITACTIVE            33079
#define ID_GEOM_PROPERTY                33080
#define ID_GEOM_COMBINE                 33081
#define ID_GEOM_DISBAND                 33082
#define ID_TRANSFORM_ROLL               33083
#define ID_TRANSFORM_PROJECT            33084
#define ID_POLYGON_SCULPT1              33085
#define ID_POLYGON_SCULPT2              33086
#define ID_POLYGON_SCULPT3              33087
#define ID_POLYGON_SCULPT4              33088
#define ID_POLYGON_SCULPT5              33089
#define ID_POINT_REMOVE                 33090
#define ID_POINT_CORNER                 33091
#define ID_POINT_CONNECT                33092
#define ID_TAG_CREATE                   33093
#define ID_EDIT_TRANSFORM               33094
#define ID_TAG_DELETE                   33095
#define ID_TAG_SETUP                    33096
#define ID_ANNO_SETUP                   33097
#define ID_ANNO_CLEAR                   33098
#define ID_ANNO_REPLACE                 33099
#define ID_PROCESS_CLEANDUPLICATED      33100
#define ID_PROCESS_CLEANOUTOFRANGE      33101
#define ID_PATH_EDGE                    33102
#define ID_ATLAS_OPEN                   33103
#define ID_ATLAS_SAVE                   33104
#define ID_ATLAS_CLOSE                  33105
#define ID_ATLAS_NEW                    33106
#define ID_MAP_COPY                     33107
#define ID_MAP_PASTE                    33108
#define ID_EDIT_CLIPIN                  33109
#define ID_EDIT_CLIPOUT                 33110
#define ID_ITEM_ATTRIBUTE               33111
#define ID_ATLAS_CLOSE2                 33111
#define ID_GEOM_SETHINT                 33112
#define ID_EDIT_INSERTGPSROUTE          33113
#define ID_DATABASE_ATTACHAAT           33114
#define ID_DATABASE_UNASSIGNATT         33115
#define ID_TOPOEDGE_CREATE              33116
#define ID_TOOL_TOPOCROSS               33117
#define ID_MAP_MOVE                     33120
#define ID_TOOL_TOPOPICK                33121
#define ID_RELEASE_VIEWER               33122
#define ID_RELEASE_POCKETPC             33123
#define ID_TAG_CREATEOPTIMALLY          33124
#define ID_TOOL_TOPOSPLIT               33125
#define ID_TOOL_TOPOEROSE               33126
#define ID_TOPOEDGE_JOIN                33127
#define ID_TOPOEDGE_CROSS               33128
#define ID_DATABASE_ATTACHPOU           33129
#define ID_VIEW_CUSTOMIZE               33130
#define ID_DATABASE_ATTACHGEO           33132
#define ID_VIEW_PANE01                  33133
#define ID_VIEW_PANE02                  33134
#define ID_VIEW_PANE04                  33136
#define ID_VIEW_PANE05                  33137
#define ID_VIEW_PANE06                  33138
#define ID_VIEW_PANE07                  33139
#define ID_VIEW_PANE08                  33140
#define ID_VIEW_PANE09                  33141
#define ID_VIEW_PANE10                  33142
#define ID_MAGNIFY_PAPER1TO1            33145
#define ID_MAGNIFY_SCREEN1TO1           33146
#define ID_MAP_REIDALL                  33147
#define ID_TOOL_DBINJECT                33148
#define ID_TOOL_DBPOSITION              33149
#define ID_TOOL_DBPICKINFO              33150
#define ID_WAMAP_VECTORTILES            33151
#define ID_WINDOW_RESETLAYOUT           33152
#define ID_ALIGN_LEFT                   33153
#define ID_ALIGN_HCENTER                33154
#define ID_ALIGN_RIGHT                  33155
#define ID_ALIGN_BOTTOM                 33156
#define ID_ALIGN_VCENTER                33157
#define ID_ALIGN_TOP                    33158
#define ID_ALIGN_CENTER                 33159
#define ID_WINDOW_CLOSEALLDOCUMENTS     33170
#define ID_WINDOW_CLOSEALL              33171
#define ID_PROJECTION_DATA              33174
#define ID_GEOGROID_RESET               33176
#define ID_GEOGROID_PLANT               33177
#define ID_LABELOID_RESET               33178
#define ID_LABELOID_PLANT               33179
#define ID_PATH_CLOSE                   33180
#define ID_RECTIFY_LOADDATUM            33181
#define ID_RECTIFY_SAVEDATUM            33182
#define ID_RECTIFY                      33183
#define ID_DATUM_LOAD                   33184
#define ID_DATUM_SAVE                   33185
#define ID_DATUM_CLEAR                  33186
#define ID_MAP_AIDPANE                  33187
#define ID_MAP_ATTFORM                  33188
#define ID_PLUGINS                      33189
#define ID_RELEASE_WEBDIWATU            33190
#define ID_MAP_SHOW                     33191
#define ID_VIEW_LABELOID                33194
#define ID_VIEW_GEOGROID                33195
#define ID_EDIT_INSERTSUBMAP            33196
#define ID_TOP_SETLABELCENTROID         33197
#define ID_TOP_SETPOLITICALCENTROID     33198
#define ID_TOP_SETLABELOID              33199
#define ID_TOP_SETGEOID                 33200
#define ID_TOP_SETGEOGROID              33201
#define ID_RELEASEWEB_VECTORPAGE        33202
#define ID_RELEASEWEB_VECTORTILE        33203
#define ID_RELEASEWEB_RASTERTILE        33204
#define ID_EDIT_CLIPRELEASE             33207
#define ID_EDIT_MASK                    33209
#define ID_MASK_RELEASE                 33210
#define ID_EDIT_MASKRELEASE             33211
#define ID_DATABASE_APPLYNAMEFROMCOUMN  33212
#define ID_DATABASE_APPLYGEOCODEFROMCOLUMN 33213
#define ID_DATABASE_APPLYNAMEF          33214
#define ID_DATABASE_APPLYGEOCODE        33215
#define ID_DATABASE_APPLYCODE           33216
#define ID_DATABASE_APPLYNAME           33217
#define ID_PLUGINS33218                 33218
#define ID_GEOGRAPH_FRAME               33219
#define ID_GEOGRAPH_GRATCULE            33247
#define ID_PREVIEW_CENTERLNG            33251
#define ID_SELECTALL_BYTYPE             33315
#define ID_GEOGRAPH_SPHERE              33316
#define ID_PREVIEW_CENTERLAT            33319
#define ID_PREVIEW_SETUP                33321
#define ID_PREVIEW_PROJECTION           33322
#define IDC_PROJECTION_NAME             33323
#define ID_FILE_RELEASE                 33331
#define ID_PREVIEW_REFRESH              33338
#define ID_PREVIEW_CONFIG               33339
#define ID_SELECTALL_BYNAME             33347
#define ID_PREVIEW_SPIN                 33348
#define ID_TOO_PREVIEWSPIN              33348
#define ID_MAGNIFY_ZOOMOUT              33350
#define ID_MAGNIFY_ZOOMIN               33351
#define ID_SLIDER2                      33352
#define ID_VIEW_LEVELSLIDER             33352
#define ID_EDIT_WRAPIN                  33354
#define ID_PROCESS_WIPEOUT              33356
#define ID_FILE_IMPORTINTO              33357
#define ID_PROCESS_NORMALIZE            33358
#define ID_POLYGON_AUTOCOLORING         33359
#define ID_REPLACE_WITHMARK             33363
#define ID_PROCESS_AUTOTAGGING          33364
#define ID_VIEW_FIXEDTAGS               33365
#define ID_VIEW_CREATEDTAGS             33365
#define ID_VIEW_DYNAMICTAGS             33366
#define ID_PROCESS_CLEANORPHAN          33369

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         33367
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           1125
#endif
#endif
